import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "fr" | "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.orientation": "Orientation",
    "nav.stages": "Stages",
    "nav.entrepreneuriat": "Entrepreneuriat",
    "nav.pricing": "Plans",
    "nav.about": "À propos",
    "nav.blog": "Blog",
    "nav.login": "Se connecter",
    "nav.register": "Commencer gratuitement",
    "nav.slogan": "Build your future",
    // Hero
    "hero.badge": "Plateforme #1 d'orientation au Maroc",
    "hero.title": "Build",
    "hero.title.highlight": "your",
    "hero.title.end": "future",
    "hero.description": "Orientation, stages et entrepreneuriat réunis dans une seule plateforme. Construisez votre parcours professionnel avec confiance et clarté.",
    "hero.cta.orientation": "Commencer mon orientation",
    "hero.cta.stages": "Explorer les stages",
    "hero.card.orientation": "Orientation",
    "hero.card.orientation.desc": "Tests interactifs et roadmaps personnalisées pour trouver votre voie.",
    "hero.card.stages": "Stages",
    "hero.card.stages.desc": "Offres de stages ciblées et ressources pour décrocher le poste idéal.",
    "hero.card.business": "Entrepreneuriat",
    "hero.card.business.desc": "Guides complets pour créer et lancer votre entreprise au Maroc.",
    "hero.stats.users": "Utilisateurs actifs",
    "hero.stats.offers": "Offres de stage",
    "hero.stats.satisfaction": "Taux de satisfaction",
    "hero.stats.partners": "Partenaires",
    // Features
    "features.badge": "Fonctionnalités",
    "features.title": "Tout ce dont vous avez besoin pour",
    "features.title.highlight": "réussir",
    "features.description": "Une plateforme complète qui vous accompagne à chaque étape de votre parcours professionnel.",
    "features.orientation.title": "Tests d'orientation intelligents",
    "features.orientation.desc": "Découvrez vos talents et aspirations grâce à nos tests interactifs basés sur la psychologie du travail.",
    "features.coaching.title": "Coaching personnalisé",
    "features.coaching.desc": "Bénéficiez d'un accompagnement sur-mesure avec nos experts en orientation et carrière.",
    "features.roadmap.title": "Roadmaps de carrière",
    "features.roadmap.desc": "Visualisez votre parcours avec des plans d'action détaillés étape par étape.",
    "features.resources.title": "Ressources premium",
    "features.resources.desc": "Accédez à des modèles de CV, lettres de motivation et guides professionnels.",
    "features.certifications.title": "Certifications reconnues",
    "features.certifications.desc": "Validez vos compétences avec des certifications valorisées par les employeurs.",
    "features.progress.title": "Suivi de progression",
    "features.progress.desc": "Suivez votre avancement et célébrez chaque étape de votre parcours.",
    // Testimonials
    "testimonials.badge": "Témoignages",
    "testimonials.title": "Ils ont transformé leur",
    "testimonials.title.highlight": "avenir",
    "testimonials.description": "Découvrez les histoires de réussite de notre communauté.",
    // CTA
    "cta.badge": "Prêt à franchir le pas ?",
    "cta.title": "Commencez votre transformation",
    "cta.title.highlight": "aujourd'hui",
    "cta.description": "Rejoignez des milliers de Marocains qui ont déjà pris leur avenir en main. Inscription gratuite, résultats garantis.",
    "cta.button": "Créer mon compte gratuit",
    "cta.button.secondary": "Voir les offres",
    "cta.note": "Aucune carte bancaire requise • Annulation à tout moment",
    // Footer
    "footer.description": "La plateforme tout-en-un pour l'orientation, les stages et l'entrepreneuriat au Maroc. Construisez votre avenir avec confiance.",
    "footer.platform": "Plateforme",
    "footer.resources": "Ressources",
    "footer.company": "Entreprise",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.rights": "Tous droits réservés.",
    // Orientation page
    "orientation.badge": "Orientation professionnelle",
    "orientation.title": "Trouvez votre",
    "orientation.title.highlight": "voie",
    "orientation.description": "Tests interactifs, parcours recommandés et roadmaps personnalisées pour construire votre avenir professionnel.",
    "orientation.cta": "Commencer le test",
    "orientation.test.badge": "Test rapide",
    "orientation.test.title": "Découvrez votre profil",
    "orientation.test.description": "Répondez à quelques questions pour découvrir les parcours qui vous correspondent.",
    "orientation.test.question": "Question",
    "orientation.test.q1": "Aimez-vous résoudre des problèmes complexes ?",
    "orientation.test.q2": "Préférez-vous travailler en équipe ou seul ?",
    "orientation.test.q3": "Êtes-vous à l'aise avec les nouvelles technologies ?",
    "orientation.test.a1": "Pas du tout",
    "orientation.test.a2": "Parfois",
    "orientation.test.a3": "Tout à fait",
    "orientation.test.complete": "Test complété !",
    "orientation.test.complete.desc": "D'après vos réponses, voici les parcours qui vous correspondent le mieux.",
    "orientation.test.results": "Voir les résultats",
    "orientation.paths.badge": "Parcours recommandés",
    "orientation.paths.title": "Explorez les opportunités",
    "orientation.paths.description": "Des parcours structurés pour vous guider vers la réussite.",
    "orientation.paths.view": "Voir le parcours",
    "orientation.roadmap.badge": "Roadmap interactive",
    "orientation.roadmap.title": "Visualisez votre parcours",
    "orientation.roadmap.title.highlight": "étape par étape",
    "orientation.roadmap.description": "Notre outil de roadmap vous permet de suivre votre progression, de planifier vos objectifs et de célébrer chaque accomplissement.",
    "orientation.roadmap.f1": "Objectifs clairs et mesurables",
    "orientation.roadmap.f2": "Suivi de progression en temps réel",
    "orientation.roadmap.f3": "Ressources adaptées à chaque étape",
    "orientation.roadmap.cta": "Créer ma roadmap",
    "orientation.roadmap.step1": "Définir vos objectifs",
    "orientation.roadmap.step2": "Suivre une formation",
    "orientation.roadmap.step3": "Obtenir un stage",
    "orientation.roadmap.step4": "Décrocher un emploi",
    // Stages page
    "stages.badge": "Offres de stages",
    "stages.title": "Trouvez le stage",
    "stages.title.highlight": "idéal",
    "stages.description": "Des centaines d'opportunités de stage au Maroc. Filtrez par ville, domaine et niveau pour trouver celui qui vous correspond.",
    "stages.search": "Rechercher un stage, une entreprise...",
    "stages.all.cities": "Toutes",
    "stages.all.domains": "Tous",
    "stages.offers.found": "offres trouvées",
    "stages.more.filters": "Plus de filtres",
    "stages.apply": "Postuler",
    "stages.learn.more": "En savoir plus",
    "stages.resources": "Ressources",
    "stages.resources.cv": "Modèles de CV",
    "stages.resources.cv.desc": "Templates professionnels adaptés au marché marocain",
    "stages.resources.letter": "Lettres de motivation",
    "stages.resources.letter.desc": "Exemples par secteur et niveau d'études",
    "stages.resources.interview": "Préparation entretien",
    "stages.resources.interview.desc": "Vidéos et conseils pour réussir vos entretiens",
    "stages.tip.title": "Conseil du jour",
    "stages.tip.content": "Personnalisez chaque candidature ! Adaptez votre CV et lettre de motivation à l'offre pour multiplier vos chances par 3.",
    "stages.tip.more": "Plus de conseils",
    "stages.posted": "Il y a",
    "stages.days": "jours",
    "stages.week": "1 semaine",
    // Entrepreneuriat page
    "entrepreneuriat.badge": "Entrepreneuriat au Maroc",
    "entrepreneuriat.title": "Lancez votre",
    "entrepreneuriat.title.highlight": "entreprise",
    "entrepreneuriat.description": "Guide complet pour créer et développer votre entreprise au Maroc. Statuts juridiques, démarches administratives, financements.",
    "entrepreneuriat.cta.guide": "Commencer le guide",
    "entrepreneuriat.cta.plan": "Créer mon business plan",
    "entrepreneuriat.steps.badge": "Les étapes clés",
    "entrepreneuriat.steps.title": "Créer votre entreprise en",
    "entrepreneuriat.steps.title.highlight": "4 étapes",
    "entrepreneuriat.steps.description": "Un parcours structuré pour transformer votre idée en réalité.",
    "entrepreneuriat.step1.title": "Définir votre projet",
    "entrepreneuriat.step1.desc": "Clarifiez votre idée, identifiez votre marché cible et validez votre concept.",
    "entrepreneuriat.step2.title": "Choisir le statut juridique",
    "entrepreneuriat.step2.desc": "SARL, SA, auto-entrepreneur... Découvrez quel statut convient à votre activité.",
    "entrepreneuriat.step3.title": "Formalités administratives",
    "entrepreneuriat.step3.desc": "Registre de commerce, CRI, CNSS... Toutes les démarches expliquées simplement.",
    "entrepreneuriat.step4.title": "Trouver des financements",
    "entrepreneuriat.step4.desc": "INDH, ANAPEC, banques, investisseurs... Explorez toutes les options.",
    "entrepreneuriat.statuts.badge": "Statuts juridiques",
    "entrepreneuriat.statuts.title": "Choisissez le bon statut",
    "entrepreneuriat.statuts.description": "Comparez les différentes formes juridiques pour trouver celle qui vous convient.",
    "entrepreneuriat.statuts.ideal": "Idéal pour :",
    "entrepreneuriat.financing.badge": "Financements",
    "entrepreneuriat.financing.title": "Trouvez les",
    "entrepreneuriat.financing.title.highlight": "financements",
    "entrepreneuriat.financing.title.end": "adaptés",
    "entrepreneuriat.financing.description": "Le Maroc offre de nombreuses opportunités de financement pour les entrepreneurs. Découvrez les programmes qui correspondent à votre projet.",
    "entrepreneuriat.stats.title": "Le saviez-vous ?",
    "entrepreneuriat.stats.1": "d'entreprises créées en 5 ans au Maroc",
    "entrepreneuriat.stats.2": "auto-entrepreneurs actifs",
    "entrepreneuriat.stats.3": "incubateurs et accélérateurs",
    "entrepreneuriat.plan.badge": "Outil gratuit",
    "entrepreneuriat.plan.title": "Créez votre",
    "entrepreneuriat.plan.title.highlight": "Business Plan",
    "entrepreneuriat.plan.description": "Notre outil simplifié vous guide étape par étape pour créer un business plan professionnel et convaincant.",
    "entrepreneuriat.plan.summary": "Résumé exécutif",
    "entrepreneuriat.plan.summary.desc": "Présentez votre vision",
    "entrepreneuriat.plan.market": "Étude de marché",
    "entrepreneuriat.plan.market.desc": "Analysez votre cible",
    "entrepreneuriat.plan.financial": "Plan financier",
    "entrepreneuriat.plan.financial.desc": "Projetez vos revenus",
    "entrepreneuriat.plan.cta": "Commencer mon business plan",
    // Pricing page
    "pricing.badge": "Plans",
    "pricing.title": "Nos",
    "pricing.title.highlight": "Plans",
    "pricing.description": "Choisissez le plan qui correspond à vos ambitions. Investissez dans votre avenir.",
    "pricing.nocard": "Aucune carte requise",
    "pricing.cancel": "Annulation gratuite",
    "pricing.support": "Support 24/7",
    "pricing.secure": "Paiement sécurisé",
    "pricing.faq.title": "Questions fréquentes",
    "pricing.faq.description": "Tout ce que vous devez savoir sur nos offres.",
    "pricing.faq.q1": "Puis-je changer de plan à tout moment ?",
    "pricing.faq.a1": "Oui, vous pouvez upgrader ou downgrader votre plan à tout moment. Les changements prennent effet immédiatement.",
    "pricing.faq.q2": "Y a-t-il un engagement minimum ?",
    "pricing.faq.a2": "Non, tous nos plans sont sans engagement. Vous pouvez annuler à tout moment sans frais.",
    "pricing.faq.q3": "Comment fonctionne l'essai gratuit ?",
    "pricing.faq.a3": "L'essai gratuit dure 7 jours. Vous pouvez tester toutes les fonctionnalités sans carte bancaire.",
    "pricing.faq.q4": "Quels moyens de paiement acceptez-vous ?",
    "pricing.faq.a4": "Nous acceptons les cartes bancaires marocaines et internationales, ainsi que les virements bancaires.",
    // Pricing plans
    "pricing.plan1.name": "Orientation Académique",
    "pricing.plan1.desc": "Pour les élèves et étudiants en quête de leur voie",
    "pricing.plan1.cta": "Commencer",
    "pricing.plan1.f1": "Tests d'orientation complets",
    "pricing.plan1.f2": "Parcours recommandés personnalisés",
    "pricing.plan1.f3": "Guide des filières au Maroc",
    "pricing.plan1.f4": "Ressources académiques",
    "pricing.plan1.f5": "Support par email",
    "pricing.plan2.name": "Stage & Travail",
    "pricing.plan2.desc": "Pour décrocher le stage ou l'emploi idéal",
    "pricing.plan2.cta": "Commencer",
    "pricing.plan2.f1": "Accès illimité aux offres de stage",
    "pricing.plan2.f2": "Modèles de CV professionnels",
    "pricing.plan2.f3": "Lettres de motivation personnalisées",
    "pricing.plan2.f4": "Coaching entretien",
    "pricing.plan2.f5": "Mise en relation entreprises",
    "pricing.plan2.f6": "Support prioritaire",
    "pricing.plan3.name": "Accompagnement Entrepreneurial",
    "pricing.plan3.desc": "Pour lancer et développer votre entreprise",
    "pricing.plan3.cta": "Commencer",
    "pricing.plan3.f1": "Guide création d'entreprise complet",
    "pricing.plan3.f2": "Templates business plan",
    "pricing.plan3.f3": "Étude de marché guidée",
    "pricing.plan3.f4": "Accès aux organismes de financement",
    "pricing.plan3.f5": "Coaching 1-to-1",
    "pricing.plan3.f6": "Relecture pitch deck",
    "pricing.plan3.f7": "Support dédié",
    // About page
    "about.badge": "À propos de NextStep",
    "about.title": "À propos de NextStep",
    "about.intro": "NextStep est une plateforme moderne dédiée à l'orientation, à l'intégration professionnelle et à l'accompagnement entrepreneurial. Dans un contexte où de nombreux jeunes au Maroc se retrouvent perdus face à leur avenir, notre mission est simple : transformer l'orientation en un véritable levier d'opportunités.",
    "about.context": "Chaque année, des milliers d'élèves choisissent une filière qui ne leur correspond pas, des étudiants abandonnent faute d'informations fiables, et des diplômés peinent à trouver un stage ou un emploi adapté. Ce constat a été le point de départ de la création de NextStep : offrir un espace clair, fiable et structuré pour guider chaque jeune, étape par étape.",
    "about.vision.title": "Notre vision",
    "about.vision.content": "Faire de l'orientation un outil stratégique permettant à chaque jeune de construire un futur solide, éclairé et aligné avec ses ambitions.",
    "about.mission.title": "Notre mission",
    "about.mission.intro": "Accompagner les jeunes dans leurs parcours :",
    "about.mission.point1.title": "Orientation académique :",
    "about.mission.point1.desc": "tests fiables et parcours recommandés.",
    "about.mission.point2.title": "Intégration professionnelle :",
    "about.mission.point2.desc": "offres de stages, modèles de CV, coaching.",
    "about.mission.point3.title": "Accompagnement entrepreneurial :",
    "about.mission.point3.desc": "guides étape par étape, outils d'étude de marché, accès aux organismes de financement.",
    "about.why.title": "Pourquoi nous avons créé NextStep ?",
    "about.why.intro": "Parce que les jeunes manquent souvent :",
    "about.why.point1": "d'informations centralisées et compréhensibles,",
    "about.why.point2": "d'un accompagnement personnalisé,",
    "about.why.point3": "d'un plan clair pour avancer.",
    "about.why.conclusion": "Notre objectif est de simplifier la prise de décision, de réduire la confusion et d'aider chaque jeune à avancer avec confiance.",
    "about.value.title": "Notre valeur ajoutée",
    "about.value.intro": "NextStep apporte :",
    "about.value.point1": "un outil simple, moderne et intuitif,",
    "about.value.point2": "un accompagnement expert et personnalisé,",
    "about.value.point3": "un accès direct aux possibilités académiques, professionnelles et entrepreneuriales,",
    "about.value.point4": "un parcours guidé pour évoluer étape par étape.",
    "about.slogan": "Build your future",
    "about.closing": "Grâce à une identité visuelle forte, un slogan inspirant et une approche centrée sur l'utilisateur, NextStep se positionne comme la plateforme incontournable pour avancer vers un avenir maîtrisé.",
  },
  en: {
    // Navbar
    "nav.orientation": "Career Guidance",
    "nav.stages": "Internships",
    "nav.entrepreneuriat": "Entrepreneurship",
    "nav.pricing": "Plans",
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.login": "Sign in",
    "nav.register": "Get started free",
    "nav.slogan": "Build your future",
    // Hero
    "hero.badge": "Morocco's #1 Career Platform",
    "hero.title": "Build",
    "hero.title.highlight": "your",
    "hero.title.end": "future",
    "hero.description": "Career guidance, internships, and entrepreneurship all in one platform. Build your professional path with confidence and clarity.",
    "hero.cta.orientation": "Start my orientation",
    "hero.cta.stages": "Explore internships",
    "hero.card.orientation": "Career Guidance",
    "hero.card.orientation.desc": "Interactive tests and personalized roadmaps to find your path.",
    "hero.card.stages": "Internships",
    "hero.card.stages.desc": "Targeted internship offers and resources to land your ideal position.",
    "hero.card.business": "Entrepreneurship",
    "hero.card.business.desc": "Complete guides to create and launch your business in Morocco.",
    "hero.stats.users": "Active users",
    "hero.stats.offers": "Internship offers",
    "hero.stats.satisfaction": "Satisfaction rate",
    "hero.stats.partners": "Partners",
    // Features
    "features.badge": "Features",
    "features.title": "Everything you need to",
    "features.title.highlight": "succeed",
    "features.description": "A complete platform that supports you at every step of your professional journey.",
    "features.orientation.title": "Smart orientation tests",
    "features.orientation.desc": "Discover your talents and aspirations through our interactive tests based on work psychology.",
    "features.coaching.title": "Personalized coaching",
    "features.coaching.desc": "Get customized support from our career and orientation experts.",
    "features.roadmap.title": "Career roadmaps",
    "features.roadmap.desc": "Visualize your journey with detailed step-by-step action plans.",
    "features.resources.title": "Premium resources",
    "features.resources.desc": "Access CV templates, cover letters, and professional guides.",
    "features.certifications.title": "Recognized certifications",
    "features.certifications.desc": "Validate your skills with certifications valued by employers.",
    "features.progress.title": "Progress tracking",
    "features.progress.desc": "Track your advancement and celebrate each step of your journey.",
    // Testimonials
    "testimonials.badge": "Testimonials",
    "testimonials.title": "They transformed their",
    "testimonials.title.highlight": "future",
    "testimonials.description": "Discover success stories from our community.",
    // CTA
    "cta.badge": "Ready to take the leap?",
    "cta.title": "Start your transformation",
    "cta.title.highlight": "today",
    "cta.description": "Join thousands of Moroccans who have already taken control of their future. Free registration, guaranteed results.",
    "cta.button": "Create my free account",
    "cta.button.secondary": "View offers",
    "cta.note": "No credit card required • Cancel anytime",
    // Footer
    "footer.description": "The all-in-one platform for career guidance, internships, and entrepreneurship in Morocco. Build your future with confidence.",
    "footer.platform": "Platform",
    "footer.resources": "Resources",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.rights": "All rights reserved.",
    // Orientation page
    "orientation.badge": "Career guidance",
    "orientation.title": "Find your",
    "orientation.title.highlight": "path",
    "orientation.description": "Interactive tests, recommended paths and personalized roadmaps to build your professional future.",
    "orientation.cta": "Start the test",
    "orientation.test.badge": "Quick test",
    "orientation.test.title": "Discover your profile",
    "orientation.test.description": "Answer a few questions to discover the paths that suit you.",
    "orientation.test.question": "Question",
    "orientation.test.q1": "Do you like solving complex problems?",
    "orientation.test.q2": "Do you prefer working in a team or alone?",
    "orientation.test.q3": "Are you comfortable with new technologies?",
    "orientation.test.a1": "Not at all",
    "orientation.test.a2": "Sometimes",
    "orientation.test.a3": "Absolutely",
    "orientation.test.complete": "Test completed!",
    "orientation.test.complete.desc": "Based on your answers, here are the paths that suit you best.",
    "orientation.test.results": "View results",
    "orientation.paths.badge": "Recommended paths",
    "orientation.paths.title": "Explore opportunities",
    "orientation.paths.description": "Structured paths to guide you to success.",
    "orientation.paths.view": "View path",
    "orientation.roadmap.badge": "Interactive roadmap",
    "orientation.roadmap.title": "Visualize your journey",
    "orientation.roadmap.title.highlight": "step by step",
    "orientation.roadmap.description": "Our roadmap tool allows you to track your progress, plan your goals and celebrate each achievement.",
    "orientation.roadmap.f1": "Clear and measurable goals",
    "orientation.roadmap.f2": "Real-time progress tracking",
    "orientation.roadmap.f3": "Resources adapted to each step",
    "orientation.roadmap.cta": "Create my roadmap",
    "orientation.roadmap.step1": "Define your goals",
    "orientation.roadmap.step2": "Follow a training",
    "orientation.roadmap.step3": "Get an internship",
    "orientation.roadmap.step4": "Land a job",
    // Stages page
    "stages.badge": "Internship offers",
    "stages.title": "Find the ideal",
    "stages.title.highlight": "internship",
    "stages.description": "Hundreds of internship opportunities in Morocco. Filter by city, field and level to find the one that suits you.",
    "stages.search": "Search for an internship, a company...",
    "stages.all.cities": "All",
    "stages.all.domains": "All",
    "stages.offers.found": "offers found",
    "stages.more.filters": "More filters",
    "stages.apply": "Apply",
    "stages.learn.more": "Learn more",
    "stages.resources": "Resources",
    "stages.resources.cv": "CV Templates",
    "stages.resources.cv.desc": "Professional templates adapted to the Moroccan market",
    "stages.resources.letter": "Cover letters",
    "stages.resources.letter.desc": "Examples by sector and education level",
    "stages.resources.interview": "Interview preparation",
    "stages.resources.interview.desc": "Videos and tips to ace your interviews",
    "stages.tip.title": "Tip of the day",
    "stages.tip.content": "Personalize each application! Adapt your CV and cover letter to multiply your chances by 3.",
    "stages.tip.more": "More tips",
    "stages.posted": "Posted",
    "stages.days": "days ago",
    "stages.week": "1 week ago",
    // Entrepreneuriat page
    "entrepreneuriat.badge": "Entrepreneurship in Morocco",
    "entrepreneuriat.title": "Launch your",
    "entrepreneuriat.title.highlight": "business",
    "entrepreneuriat.description": "Complete guide to create and develop your business in Morocco. Legal statuses, administrative procedures, financing.",
    "entrepreneuriat.cta.guide": "Start the guide",
    "entrepreneuriat.cta.plan": "Create my business plan",
    "entrepreneuriat.steps.badge": "Key steps",
    "entrepreneuriat.steps.title": "Create your business in",
    "entrepreneuriat.steps.title.highlight": "4 steps",
    "entrepreneuriat.steps.description": "A structured path to turn your idea into reality.",
    "entrepreneuriat.step1.title": "Define your project",
    "entrepreneuriat.step1.desc": "Clarify your idea, identify your target market and validate your concept.",
    "entrepreneuriat.step2.title": "Choose legal status",
    "entrepreneuriat.step2.desc": "SARL, SA, auto-entrepreneur... Discover which status suits your activity.",
    "entrepreneuriat.step3.title": "Administrative formalities",
    "entrepreneuriat.step3.desc": "Trade register, CRI, CNSS... All procedures explained simply.",
    "entrepreneuriat.step4.title": "Find financing",
    "entrepreneuriat.step4.desc": "INDH, ANAPEC, banks, investors... Explore all options.",
    "entrepreneuriat.statuts.badge": "Legal statuses",
    "entrepreneuriat.statuts.title": "Choose the right status",
    "entrepreneuriat.statuts.description": "Compare different legal forms to find the one that suits you.",
    "entrepreneuriat.statuts.ideal": "Ideal for:",
    "entrepreneuriat.financing.badge": "Financing",
    "entrepreneuriat.financing.title": "Find the right",
    "entrepreneuriat.financing.title.highlight": "financing",
    "entrepreneuriat.financing.title.end": "options",
    "entrepreneuriat.financing.description": "Morocco offers many financing opportunities for entrepreneurs. Discover the programs that match your project.",
    "entrepreneuriat.stats.title": "Did you know?",
    "entrepreneuriat.stats.1": "businesses created in 5 years in Morocco",
    "entrepreneuriat.stats.2": "active auto-entrepreneurs",
    "entrepreneuriat.stats.3": "incubators and accelerators",
    "entrepreneuriat.plan.badge": "Free tool",
    "entrepreneuriat.plan.title": "Create your",
    "entrepreneuriat.plan.title.highlight": "Business Plan",
    "entrepreneuriat.plan.description": "Our simplified tool guides you step by step to create a professional and convincing business plan.",
    "entrepreneuriat.plan.summary": "Executive summary",
    "entrepreneuriat.plan.summary.desc": "Present your vision",
    "entrepreneuriat.plan.market": "Market study",
    "entrepreneuriat.plan.market.desc": "Analyze your target",
    "entrepreneuriat.plan.financial": "Financial plan",
    "entrepreneuriat.plan.financial.desc": "Project your revenues",
    "entrepreneuriat.plan.cta": "Start my business plan",
    // Pricing page
    "pricing.badge": "Plans",
    "pricing.title": "Our",
    "pricing.title.highlight": "Plans",
    "pricing.description": "Choose the plan that matches your ambitions. Invest in your future.",
    "pricing.nocard": "No card required",
    "pricing.cancel": "Free cancellation",
    "pricing.support": "24/7 support",
    "pricing.secure": "Secure payment",
    "pricing.faq.title": "Frequently asked questions",
    "pricing.faq.description": "Everything you need to know about our offers.",
    "pricing.faq.q1": "Can I change plans anytime?",
    "pricing.faq.a1": "Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately.",
    "pricing.faq.q2": "Is there a minimum commitment?",
    "pricing.faq.a2": "No, all our plans are commitment-free. You can cancel anytime without fees.",
    "pricing.faq.q3": "How does the free trial work?",
    "pricing.faq.a3": "The free trial lasts 7 days. You can test all features without a credit card.",
    "pricing.faq.q4": "What payment methods do you accept?",
    "pricing.faq.a4": "We accept Moroccan and international bank cards, as well as bank transfers.",
    // Pricing plans
    "pricing.plan1.name": "Academic Orientation",
    "pricing.plan1.desc": "For students seeking their path",
    "pricing.plan1.cta": "Get Started",
    "pricing.plan1.f1": "Complete orientation tests",
    "pricing.plan1.f2": "Personalized recommended paths",
    "pricing.plan1.f3": "Guide to programs in Morocco",
    "pricing.plan1.f4": "Academic resources",
    "pricing.plan1.f5": "Email support",
    "pricing.plan2.name": "Internship & Work",
    "pricing.plan2.desc": "To land the ideal internship or job",
    "pricing.plan2.cta": "Get Started",
    "pricing.plan2.f1": "Unlimited access to internship offers",
    "pricing.plan2.f2": "Professional CV templates",
    "pricing.plan2.f3": "Personalized cover letters",
    "pricing.plan2.f4": "Interview coaching",
    "pricing.plan2.f5": "Company connections",
    "pricing.plan2.f6": "Priority support",
    "pricing.plan3.name": "Entrepreneurial Support",
    "pricing.plan3.desc": "To launch and grow your business",
    "pricing.plan3.cta": "Get Started",
    "pricing.plan3.f1": "Complete business creation guide",
    "pricing.plan3.f2": "Business plan templates",
    "pricing.plan3.f3": "Guided market research",
    "pricing.plan3.f4": "Access to funding organizations",
    "pricing.plan3.f5": "1-on-1 coaching",
    "pricing.plan3.f6": "Pitch deck review",
    "pricing.plan3.f7": "Dedicated support",
    // About page
    "about.badge": "About NextStep",
    "about.title": "About NextStep",
    "about.intro": "NextStep is a modern platform dedicated to career guidance, professional integration, and entrepreneurial support. In a context where many young people in Morocco find themselves lost facing their future, our mission is simple: transform orientation into a real lever of opportunities.",
    "about.context": "Every year, thousands of students choose a field that doesn't suit them, students drop out due to lack of reliable information, and graduates struggle to find a suitable internship or job. This observation was the starting point for creating NextStep: to offer a clear, reliable, and structured space to guide every young person, step by step.",
    "about.vision.title": "Our Vision",
    "about.vision.content": "To make orientation a strategic tool allowing every young person to build a solid future, enlightened and aligned with their ambitions.",
    "about.mission.title": "Our Mission",
    "about.mission.intro": "Supporting young people in their journey:",
    "about.mission.point1.title": "Academic orientation:",
    "about.mission.point1.desc": "reliable tests and recommended paths.",
    "about.mission.point2.title": "Professional integration:",
    "about.mission.point2.desc": "internship offers, CV templates, coaching.",
    "about.mission.point3.title": "Entrepreneurial support:",
    "about.mission.point3.desc": "step-by-step guides, market research tools, access to funding organizations.",
    "about.why.title": "Why We Created NextStep?",
    "about.why.intro": "Because young people often lack:",
    "about.why.point1": "centralized and understandable information,",
    "about.why.point2": "personalized support,",
    "about.why.point3": "a clear plan to move forward.",
    "about.why.conclusion": "Our goal is to simplify decision-making, reduce confusion, and help every young person move forward with confidence.",
    "about.value.title": "Our Added Value",
    "about.value.intro": "NextStep brings:",
    "about.value.point1": "a simple, modern and intuitive tool,",
    "about.value.point2": "expert and personalized support,",
    "about.value.point3": "direct access to academic, professional and entrepreneurial opportunities,",
    "about.value.point4": "a guided journey to evolve step by step.",
    "about.slogan": "Build your future",
    "about.closing": "With a strong visual identity, an inspiring slogan, and a user-centered approach, NextStep positions itself as the essential platform for moving towards a mastered future.",
  },
  ar: {
    // Navbar
    "nav.orientation": "التوجيه المهني",
    "nav.stages": "التدريب",
    "nav.entrepreneuriat": "ريادة الأعمال",
    "nav.pricing": "الخطط",
    "nav.about": "من نحن",
    "nav.blog": "المدونة",
    "nav.login": "تسجيل الدخول",
    "nav.register": "ابدأ مجاناً",
    "nav.slogan": "Build your future",
    // Hero
    "hero.badge": "المنصة الأولى للتوجيه في المغرب",
    "hero.title": "Build",
    "hero.title.highlight": "your",
    "hero.title.end": "future",
    "hero.description": "التوجيه المهني والتدريب وريادة الأعمال في منصة واحدة. ابنِ مسارك المهني بثقة ووضوح.",
    "hero.cta.orientation": "ابدأ توجيهي",
    "hero.cta.stages": "استكشف التدريبات",
    "hero.card.orientation": "التوجيه المهني",
    "hero.card.orientation.desc": "اختبارات تفاعلية وخطط مخصصة لإيجاد طريقك.",
    "hero.card.stages": "التدريب",
    "hero.card.stages.desc": "عروض تدريب مستهدفة وموارد للحصول على الوظيفة المثالية.",
    "hero.card.business": "ريادة الأعمال",
    "hero.card.business.desc": "أدلة شاملة لإنشاء وإطلاق مشروعك في المغرب.",
    "hero.stats.users": "مستخدم نشط",
    "hero.stats.offers": "عرض تدريب",
    "hero.stats.satisfaction": "معدل الرضا",
    "hero.stats.partners": "شريك",
    // Features
    "features.badge": "المميزات",
    "features.title": "كل ما تحتاجه لتحقيق",
    "features.title.highlight": "النجاح",
    "features.description": "منصة متكاملة ترافقك في كل خطوة من مسارك المهني.",
    "features.orientation.title": "اختبارات توجيه ذكية",
    "features.orientation.desc": "اكتشف مواهبك وتطلعاتك من خلال اختباراتنا التفاعلية.",
    "features.coaching.title": "تدريب شخصي",
    "features.coaching.desc": "احصل على دعم مخصص من خبرائنا في التوجيه والمهنة.",
    "features.roadmap.title": "خرائط طريق مهنية",
    "features.roadmap.desc": "تصور رحلتك بخطط عمل مفصلة خطوة بخطوة.",
    "features.resources.title": "موارد متميزة",
    "features.resources.desc": "الوصول إلى قوالب السيرة الذاتية ورسائل التقديم.",
    "features.certifications.title": "شهادات معترف بها",
    "features.certifications.desc": "صادق على مهاراتك بشهادات يقدرها أصحاب العمل.",
    "features.progress.title": "تتبع التقدم",
    "features.progress.desc": "تابع تقدمك واحتفل بكل خطوة من رحلتك.",
    // Testimonials
    "testimonials.badge": "شهادات",
    "testimonials.title": "لقد غيروا",
    "testimonials.title.highlight": "مستقبلهم",
    "testimonials.description": "اكتشف قصص نجاح مجتمعنا.",
    // CTA
    "cta.badge": "مستعد للانطلاق؟",
    "cta.title": "ابدأ تحولك",
    "cta.title.highlight": "اليوم",
    "cta.description": "انضم إلى آلاف المغاربة الذين تحكموا في مستقبلهم. تسجيل مجاني، نتائج مضمونة.",
    "cta.button": "إنشاء حسابي المجاني",
    "cta.button.secondary": "عرض العروض",
    "cta.note": "لا حاجة لبطاقة ائتمان • إلغاء في أي وقت",
    // Footer
    "footer.description": "المنصة الشاملة للتوجيه والتدريب وريادة الأعمال في المغرب. ابنِ مستقبلك بثقة.",
    "footer.platform": "المنصة",
    "footer.resources": "الموارد",
    "footer.company": "الشركة",
    "footer.contact": "اتصل بنا",
    "footer.legal": "قانوني",
    "footer.rights": "جميع الحقوق محفوظة.",
    // Orientation page
    "orientation.badge": "التوجيه المهني",
    "orientation.title": "اعثر على",
    "orientation.title.highlight": "طريقك",
    "orientation.description": "اختبارات تفاعلية ومسارات موصى بها وخرائط طريق مخصصة لبناء مستقبلك المهني.",
    "orientation.cta": "ابدأ الاختبار",
    "orientation.test.badge": "اختبار سريع",
    "orientation.test.title": "اكتشف ملفك الشخصي",
    "orientation.test.description": "أجب على بعض الأسئلة لاكتشاف المسارات المناسبة لك.",
    "orientation.test.question": "سؤال",
    "orientation.test.q1": "هل تحب حل المشاكل المعقدة؟",
    "orientation.test.q2": "هل تفضل العمل في فريق أم بمفردك؟",
    "orientation.test.q3": "هل أنت مرتاح مع التقنيات الجديدة؟",
    "orientation.test.a1": "ليس على الإطلاق",
    "orientation.test.a2": "أحياناً",
    "orientation.test.a3": "بالتأكيد",
    "orientation.test.complete": "تم الاختبار!",
    "orientation.test.complete.desc": "بناءً على إجاباتك، إليك المسارات الأنسب لك.",
    "orientation.test.results": "عرض النتائج",
    "orientation.paths.badge": "مسارات موصى بها",
    "orientation.paths.title": "استكشف الفرص",
    "orientation.paths.description": "مسارات منظمة لتوجيهك نحو النجاح.",
    "orientation.paths.view": "عرض المسار",
    "orientation.roadmap.badge": "خريطة طريق تفاعلية",
    "orientation.roadmap.title": "تصور رحلتك",
    "orientation.roadmap.title.highlight": "خطوة بخطوة",
    "orientation.roadmap.description": "تتيح لك أداة خريطة الطريق تتبع تقدمك والتخطيط لأهدافك والاحتفال بكل إنجاز.",
    "orientation.roadmap.f1": "أهداف واضحة وقابلة للقياس",
    "orientation.roadmap.f2": "تتبع التقدم في الوقت الفعلي",
    "orientation.roadmap.f3": "موارد مكيفة لكل خطوة",
    "orientation.roadmap.cta": "إنشاء خريطتي",
    "orientation.roadmap.step1": "حدد أهدافك",
    "orientation.roadmap.step2": "اتبع تدريباً",
    "orientation.roadmap.step3": "احصل على تدريب",
    "orientation.roadmap.step4": "احصل على وظيفة",
    // Stages page
    "stages.badge": "عروض التدريب",
    "stages.title": "اعثر على التدريب",
    "stages.title.highlight": "المثالي",
    "stages.description": "مئات فرص التدريب في المغرب. قم بالتصفية حسب المدينة والمجال والمستوى.",
    "stages.search": "ابحث عن تدريب، شركة...",
    "stages.all.cities": "الكل",
    "stages.all.domains": "الكل",
    "stages.offers.found": "عروض موجودة",
    "stages.more.filters": "المزيد من الفلاتر",
    "stages.apply": "تقدم",
    "stages.learn.more": "اعرف المزيد",
    "stages.resources": "الموارد",
    "stages.resources.cv": "قوالب السيرة الذاتية",
    "stages.resources.cv.desc": "قوالب احترافية مكيفة للسوق المغربي",
    "stages.resources.letter": "رسائل التقديم",
    "stages.resources.letter.desc": "أمثلة حسب القطاع ومستوى التعليم",
    "stages.resources.interview": "التحضير للمقابلة",
    "stages.resources.interview.desc": "فيديوهات ونصائح لنجاح مقابلاتك",
    "stages.tip.title": "نصيحة اليوم",
    "stages.tip.content": "خصص كل طلب! قم بتكييف سيرتك الذاتية ورسالة التقديم لمضاعفة فرصك بمقدار 3.",
    "stages.tip.more": "المزيد من النصائح",
    "stages.posted": "منذ",
    "stages.days": "أيام",
    "stages.week": "أسبوع واحد",
    // Entrepreneuriat page
    "entrepreneuriat.badge": "ريادة الأعمال في المغرب",
    "entrepreneuriat.title": "أطلق",
    "entrepreneuriat.title.highlight": "مشروعك",
    "entrepreneuriat.description": "دليل شامل لإنشاء وتطوير عملك في المغرب. الأوضاع القانونية، الإجراءات الإدارية، التمويل.",
    "entrepreneuriat.cta.guide": "ابدأ الدليل",
    "entrepreneuriat.cta.plan": "إنشاء خطة عملي",
    "entrepreneuriat.steps.badge": "الخطوات الرئيسية",
    "entrepreneuriat.steps.title": "أنشئ مشروعك في",
    "entrepreneuriat.steps.title.highlight": "4 خطوات",
    "entrepreneuriat.steps.description": "مسار منظم لتحويل فكرتك إلى واقع.",
    "entrepreneuriat.step1.title": "حدد مشروعك",
    "entrepreneuriat.step1.desc": "وضح فكرتك، حدد سوقك المستهدف وتحقق من مفهومك.",
    "entrepreneuriat.step2.title": "اختر الوضع القانوني",
    "entrepreneuriat.step2.desc": "SARL، SA، المقاول الذاتي... اكتشف الوضع المناسب لنشاطك.",
    "entrepreneuriat.step3.title": "الإجراءات الإدارية",
    "entrepreneuriat.step3.desc": "السجل التجاري، CRI، CNSS... جميع الإجراءات موضحة ببساطة.",
    "entrepreneuriat.step4.title": "ابحث عن التمويل",
    "entrepreneuriat.step4.desc": "INDH، ANAPEC، البنوك، المستثمرون... استكشف جميع الخيارات.",
    "entrepreneuriat.statuts.badge": "الأوضاع القانونية",
    "entrepreneuriat.statuts.title": "اختر الوضع المناسب",
    "entrepreneuriat.statuts.description": "قارن بين الأشكال القانونية المختلفة للعثور على ما يناسبك.",
    "entrepreneuriat.statuts.ideal": "مثالي لـ:",
    "entrepreneuriat.financing.badge": "التمويل",
    "entrepreneuriat.financing.title": "اعثر على",
    "entrepreneuriat.financing.title.highlight": "التمويل",
    "entrepreneuriat.financing.title.end": "المناسب",
    "entrepreneuriat.financing.description": "يقدم المغرب العديد من فرص التمويل للمقاولين. اكتشف البرامج المناسبة لمشروعك.",
    "entrepreneuriat.stats.title": "هل تعلم؟",
    "entrepreneuriat.stats.1": "شركات أُنشئت في 5 سنوات في المغرب",
    "entrepreneuriat.stats.2": "مقاول ذاتي نشط",
    "entrepreneuriat.stats.3": "حاضنات ومسرعات",
    "entrepreneuriat.plan.badge": "أداة مجانية",
    "entrepreneuriat.plan.title": "أنشئ",
    "entrepreneuriat.plan.title.highlight": "خطة عملك",
    "entrepreneuriat.plan.description": "أداتنا المبسطة ترشدك خطوة بخطوة لإنشاء خطة عمل احترافية ومقنعة.",
    "entrepreneuriat.plan.summary": "الملخص التنفيذي",
    "entrepreneuriat.plan.summary.desc": "قدم رؤيتك",
    "entrepreneuriat.plan.market": "دراسة السوق",
    "entrepreneuriat.plan.market.desc": "حلل جمهورك المستهدف",
    "entrepreneuriat.plan.financial": "الخطة المالية",
    "entrepreneuriat.plan.financial.desc": "توقع إيراداتك",
    "entrepreneuriat.plan.cta": "ابدأ خطة عملي",
    // Pricing page
    "pricing.badge": "الخطط",
    "pricing.title": "",
    "pricing.title.highlight": "خططنا",
    "pricing.description": "اختر الخطة التي تناسب طموحاتك. استثمر في مستقبلك.",
    "pricing.nocard": "لا حاجة لبطاقة",
    "pricing.cancel": "إلغاء مجاني",
    "pricing.support": "دعم 24/7",
    "pricing.secure": "دفع آمن",
    "pricing.faq.title": "الأسئلة الشائعة",
    "pricing.faq.description": "كل ما تحتاج معرفته عن عروضنا.",
    "pricing.faq.q1": "هل يمكنني تغيير الخطة في أي وقت؟",
    "pricing.faq.a1": "نعم، يمكنك الترقية أو الرجوع في أي وقت. التغييرات تطبق فوراً.",
    "pricing.faq.q2": "هل هناك التزام أدنى؟",
    "pricing.faq.a2": "لا، جميع خططنا بدون التزام. يمكنك الإلغاء في أي وقت بدون رسوم.",
    "pricing.faq.q3": "كيف تعمل التجربة المجانية؟",
    "pricing.faq.a3": "التجربة المجانية تدوم 7 أيام. يمكنك اختبار جميع الميزات بدون بطاقة ائتمان.",
    "pricing.faq.q4": "ما وسائل الدفع التي تقبلونها؟",
    "pricing.faq.a4": "نقبل البطاقات البنكية المغربية والدولية، وكذلك التحويلات البنكية.",
    // Pricing plans
    "pricing.plan1.name": "التوجيه الأكاديمي",
    "pricing.plan1.desc": "للطلاب الباحثين عن طريقهم",
    "pricing.plan1.cta": "ابدأ الآن",
    "pricing.plan1.f1": "اختبارات توجيه شاملة",
    "pricing.plan1.f2": "مسارات موصى بها مخصصة",
    "pricing.plan1.f3": "دليل التخصصات في المغرب",
    "pricing.plan1.f4": "موارد أكاديمية",
    "pricing.plan1.f5": "دعم بالبريد الإلكتروني",
    "pricing.plan2.name": "التدريب والعمل",
    "pricing.plan2.desc": "للحصول على التدريب أو الوظيفة المثالية",
    "pricing.plan2.cta": "ابدأ الآن",
    "pricing.plan2.f1": "وصول غير محدود لعروض التدريب",
    "pricing.plan2.f2": "قوالب سيرة ذاتية احترافية",
    "pricing.plan2.f3": "رسائل تقديم مخصصة",
    "pricing.plan2.f4": "تدريب على المقابلات",
    "pricing.plan2.f5": "ربط مع الشركات",
    "pricing.plan2.f6": "دعم أولوية",
    "pricing.plan3.name": "دعم ريادة الأعمال",
    "pricing.plan3.desc": "لإطلاق وتطوير مشروعك",
    "pricing.plan3.cta": "ابدأ الآن",
    "pricing.plan3.f1": "دليل إنشاء مشروع شامل",
    "pricing.plan3.f2": "قوالب خطة العمل",
    "pricing.plan3.f3": "دراسة سوق موجهة",
    "pricing.plan3.f4": "الوصول لمنظمات التمويل",
    "pricing.plan3.f5": "تدريب فردي",
    "pricing.plan3.f6": "مراجعة عرض المشروع",
    "pricing.plan3.f7": "دعم مخصص",
    // About page
    "about.badge": "من نحن",
    "about.title": "من نحن - NextStep",
    "about.intro": "NextStep هي منصة حديثة مخصصة للتوجيه والاندماج المهني ودعم ريادة الأعمال. في سياق حيث يجد العديد من الشباب في المغرب أنفسهم تائهين أمام مستقبلهم، مهمتنا بسيطة: تحويل التوجيه إلى رافعة حقيقية للفرص.",
    "about.context": "كل عام، يختار آلاف الطلاب تخصصاً لا يناسبهم، ويتخلى طلاب آخرون بسبب نقص المعلومات الموثوقة، ويجد الخريجون صعوبة في إيجاد تدريب أو وظيفة مناسبة. كانت هذه الملاحظة نقطة البداية لإنشاء NextStep: تقديم مساحة واضحة وموثوقة ومنظمة لتوجيه كل شاب، خطوة بخطوة.",
    "about.vision.title": "رؤيتنا",
    "about.vision.content": "جعل التوجيه أداة استراتيجية تمكن كل شاب من بناء مستقبل متين ومستنير ومتوافق مع طموحاته.",
    "about.mission.title": "مهمتنا",
    "about.mission.intro": "مرافقة الشباب في مساراتهم:",
    "about.mission.point1.title": "التوجيه الأكاديمي:",
    "about.mission.point1.desc": "اختبارات موثوقة ومسارات موصى بها.",
    "about.mission.point2.title": "الاندماج المهني:",
    "about.mission.point2.desc": "عروض تدريب، قوالب سيرة ذاتية، تدريب.",
    "about.mission.point3.title": "دعم ريادة الأعمال:",
    "about.mission.point3.desc": "أدلة خطوة بخطوة، أدوات دراسة السوق، الوصول لمنظمات التمويل.",
    "about.why.title": "لماذا أنشأنا NextStep؟",
    "about.why.intro": "لأن الشباب غالباً ما يفتقرون إلى:",
    "about.why.point1": "معلومات مركزة ومفهومة،",
    "about.why.point2": "مرافقة شخصية،",
    "about.why.point3": "خطة واضحة للتقدم.",
    "about.why.conclusion": "هدفنا هو تبسيط اتخاذ القرار، تقليل الارتباك، ومساعدة كل شاب على التقدم بثقة.",
    "about.value.title": "قيمتنا المضافة",
    "about.value.intro": "تقدم NextStep:",
    "about.value.point1": "أداة بسيطة وحديثة وبديهية،",
    "about.value.point2": "مرافقة خبيرة ومخصصة،",
    "about.value.point3": "وصول مباشر للفرص الأكاديمية والمهنية وريادة الأعمال،",
    "about.value.point4": "مسار موجه للتطور خطوة بخطوة.",
    "about.slogan": "Build your future",
    "about.closing": "بفضل هوية بصرية قوية وشعار ملهم ونهج متمحور حول المستخدم، تتموضع NextStep كمنصة أساسية للتقدم نحو مستقبل متقن.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
