import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "fr" | "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.orientation": "Orientation",
    "nav.stages": "Stages",
    "nav.entrepreneuriat": "Entrepreneuriat",
    "nav.pricing": "Plans",
    "nav.about": "À propos",
    "nav.blog": "Blog",
    "nav.login": "Se connecter",
    "nav.register": "Commencer gratuitement",
    "nav.slogan": "Build your future",
    // Hero
    "hero.badge": "Plateforme #1 d'orientation au Maroc",
    "hero.title": "Build",
    "hero.title.highlight": "your",
    "hero.title.end": "future",
    "hero.description": "Orientation, stages et entrepreneuriat réunis dans une seule plateforme. Construisez votre parcours professionnel avec confiance et clarté.",
    "hero.cta.orientation": "Commencer mon orientation",
    "hero.cta.stages": "Explorer les stages",
    "hero.card.orientation": "Orientation",
    "hero.card.orientation.desc": "Tests interactifs et roadmaps personnalisées pour trouver votre voie.",
    "hero.card.stagesjobs": "Stages & Offres de travail",
    "hero.card.stagesjobs.desc": "Offres de stages et emplois ciblées et ressources pour décrocher le poste idéal.",
    "hero.card.business": "Entrepreneuriat",
    "hero.card.business.desc": "Guides complets pour créer et lancer votre entreprise au Maroc.",
    "hero.stats.users": "Utilisateurs actifs",
    "hero.stats.offers": "Offres de stage",
    "hero.stats.satisfaction": "Taux de satisfaction",
    "hero.stats.partners": "Partenaires",
    // Features
    "features.badge": "Fonctionnalités",
    "features.title": "Tout ce dont vous avez besoin pour",
    "features.title.highlight": "réussir",
    "features.description": "Une plateforme complète qui vous accompagne à chaque étape de votre parcours professionnel.",
    "features.orientation.title": "Tests d'orientation intelligents",
    "features.orientation.desc": "Découvrez vos talents et aspirations grâce à nos tests interactifs basés sur la psychologie du travail.",
    "features.coaching.title": "Coaching personnalisé",
    "features.coaching.desc": "Bénéficiez d'un accompagnement sur-mesure avec nos experts en orientation et carrière.",
    "features.roadmap.title": "Roadmaps de carrière",
    "features.roadmap.desc": "Visualisez votre parcours avec des plans d'action détaillés étape par étape.",
    "features.resources.title": "Ressources premium",
    "features.resources.desc": "Accédez à des modèles de CV, lettres de motivation et guides professionnels.",
    "features.certifications.title": "Certifications reconnues",
    "features.certifications.desc": "Validez vos compétences avec des certifications valorisées par les employeurs.",
    "features.progress.title": "Suivi de progression",
    "features.progress.desc": "Suivez votre avancement et célébrez chaque étape de votre parcours.",
    // Testimonials
    "testimonials.badge": "Témoignages",
    "testimonials.title": "Ils ont transformé leur",
    "testimonials.title.highlight": "avenir",
    "testimonials.description": "Découvrez les histoires de réussite de notre communauté.",
    // CTA
    "cta.badge": "Prêt à franchir le pas ?",
    "cta.title": "Commencez votre transformation",
    "cta.title.highlight": "aujourd'hui",
    "cta.description": "Rejoignez des milliers de Marocains qui ont déjà pris leur avenir en main. Inscription gratuite, résultats garantis.",
    "cta.button": "Créer mon compte gratuit",
    "cta.button.secondary": "Voir les offres",
    "cta.note": "Aucune carte bancaire requise • Annulation à tout moment",
    // Footer
    "footer.description": "La plateforme tout-en-un pour l'orientation, les stages, les offres d'emploi et l'entrepreneuriat au Maroc. Construisez votre avenir avec confiance.",
    "footer.platform": "Plateforme",
    "footer.resources": "Ressources",
    "footer.stages": "Stages",
    "footer.jobs": "Offres d'emploi",
    "footer.blog": "Actualités & Conseils",
    "footer.faq": "FAQ",
    "footer.company": "Entreprise",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.rights": "Tous droits réservés.",
    // Orientation page
    "orientation.badge": "Orientation professionnelle",
    "orientation.title": "Trouvez votre",
    "orientation.title.highlight": "voie",
    "orientation.description": "Tests interactifs, parcours recommandés et roadmaps personnalisées pour construire votre avenir professionnel.",
    "orientation.cta": "Commencer le test",
    "orientation.test.badge": "Test rapide",
    "orientation.test.title": "Découvrez votre profil",
    "orientation.test.description": "Répondez à quelques questions pour découvrir les parcours qui vous correspondent.",
    "orientation.test.question": "Question",
    "orientation.test.q1": "Aimez-vous résoudre des problèmes complexes ?",
    "orientation.test.q2": "Préférez-vous travailler en équipe ou seul ?",
    "orientation.test.q3": "Êtes-vous à l'aise avec les nouvelles technologies ?",
    "orientation.test.a1": "Pas du tout",
    "orientation.test.a2": "Parfois",
    "orientation.test.a3": "Tout à fait",
    "orientation.test.complete": "Test complété !",
    "orientation.test.complete.desc": "D'après vos réponses, voici les parcours qui vous correspondent le mieux.",
    "orientation.test.results": "Voir les résultats",
    "orientation.paths.badge": "Parcours recommandés",
    "orientation.paths.title": "Explorez les opportunités",
    "orientation.paths.description": "Des parcours structurés pour vous guider vers la réussite.",
    "orientation.paths.view": "Voir le parcours",
    "orientation.roadmap.badge": "Roadmap interactive",
    "orientation.roadmap.title": "Visualisez votre parcours",
    "orientation.roadmap.title.highlight": "étape par étape",
    "orientation.roadmap.description": "Notre outil de roadmap vous permet de suivre votre progression, de planifier vos objectifs et de célébrer chaque accomplissement.",
    "orientation.roadmap.f1": "Objectifs clairs et mesurables",
    "orientation.roadmap.f2": "Suivi de progression en temps réel",
    "orientation.roadmap.f3": "Ressources adaptées à chaque étape",
    "orientation.roadmap.cta": "Créer ma roadmap",
    "orientation.roadmap.step1": "Définir vos objectifs",
    "orientation.roadmap.step2": "Suivre une formation",
    "orientation.roadmap.step3": "Obtenir un stage",
    "orientation.roadmap.step4": "Décrocher un emploi",
    // Stages page
    "stages.badge": "Offres de stages",
    "stages.title": "Trouvez le stage",
    "stages.title.highlight": "idéal",
    "stages.description": "Des centaines d'opportunités de stage au Maroc. Filtrez par ville, domaine et niveau pour trouver celui qui vous correspond.",
    "stages.search": "Rechercher un stage, une entreprise...",
    "stages.all.cities": "Toutes",
    "stages.all.domains": "Tous",
    "stages.offers.found": "offres trouvées",
    "stages.more.filters": "Plus de filtres",
    "stages.apply": "Postuler",
    "stages.learn.more": "En savoir plus",
    "stages.resources": "Ressources",
    "stages.resources.cv": "Modèles de CV",
    "stages.resources.cv.desc": "Templates professionnels adaptés au marché marocain",
    "stages.resources.letter": "Lettres de motivation",
    "stages.resources.letter.desc": "Exemples par secteur et niveau d'études",
    "stages.resources.interview": "Préparation entretien",
    "stages.resources.interview.desc": "Vidéos et conseils pour réussir vos entretiens",
    "stages.tip.title": "Conseil du jour",
    "stages.tip.content": "Personnalisez chaque candidature ! Adaptez votre CV et lettre de motivation à l'offre pour multiplier vos chances par 3.",
    "stages.tip.more": "Plus de conseils",
    "stages.posted": "Il y a",
    "stages.days": "jours",
    "stages.week": "1 semaine",
    // Entrepreneuriat page
    "entrepreneuriat.badge": "Entrepreneuriat au Maroc",
    "entrepreneuriat.title": "Lancez votre",
    "entrepreneuriat.title.highlight": "entreprise",
    "entrepreneuriat.description": "Guide complet pour créer et développer votre entreprise au Maroc. Statuts juridiques, démarches administratives, financements.",
    "entrepreneuriat.cta.guide": "Commencer le guide",
    "entrepreneuriat.cta.plan": "Créer mon business plan",
    "entrepreneuriat.steps.badge": "Les étapes clés",
    "entrepreneuriat.steps.title": "Créer votre entreprise en",
    "entrepreneuriat.steps.title.highlight": "4 étapes",
    "entrepreneuriat.steps.description": "Un parcours structuré pour transformer votre idée en réalité.",
    "entrepreneuriat.step1.title": "Définir votre projet",
    "entrepreneuriat.step1.desc": "Clarifiez votre idée, identifiez votre marché cible et validez votre concept.",
    "entrepreneuriat.step2.title": "Choisir le statut juridique",
    "entrepreneuriat.step2.desc": "SARL, SA, auto-entrepreneur... Découvrez quel statut convient à votre activité.",
    "entrepreneuriat.step3.title": "Formalités administratives",
    "entrepreneuriat.step3.desc": "Registre de commerce, CRI, CNSS... Toutes les démarches expliquées simplement.",
    "entrepreneuriat.step4.title": "Trouver des financements",
    "entrepreneuriat.step4.desc": "INDH, ANAPEC, banques, investisseurs... Explorez toutes les options.",
    "entrepreneuriat.statuts.badge": "Statuts juridiques",
    "entrepreneuriat.statuts.title": "Choisissez le bon statut",
    "entrepreneuriat.statuts.description": "Comparez les différentes formes juridiques pour trouver celle qui vous convient.",
    "entrepreneuriat.statuts.ideal": "Idéal pour :",
    "entrepreneuriat.financing.badge": "Financements",
    "entrepreneuriat.financing.title": "Trouvez les",
    "entrepreneuriat.financing.title.highlight": "financements",
    "entrepreneuriat.financing.title.end": "adaptés",
    "entrepreneuriat.financing.description": "Le Maroc offre de nombreuses opportunités de financement pour les entrepreneurs. Découvrez les programmes qui correspondent à votre projet.",
    "entrepreneuriat.stats.title": "Le saviez-vous ?",
    "entrepreneuriat.stats.1": "d'entreprises créées en 5 ans au Maroc",
    "entrepreneuriat.stats.2": "auto-entrepreneurs actifs",
    "entrepreneuriat.stats.3": "incubateurs et accélérateurs",
    "entrepreneuriat.plan.badge": "Outil gratuit",
    "entrepreneuriat.plan.title": "Créez votre",
    "entrepreneuriat.plan.title.highlight": "Business Plan",
    "entrepreneuriat.plan.description": "Notre outil simplifié vous guide étape par étape pour créer un business plan professionnel et convaincant.",
    "entrepreneuriat.plan.summary": "Résumé exécutif",
    "entrepreneuriat.plan.summary.desc": "Présentez votre vision",
    "entrepreneuriat.plan.market": "Étude de marché",
    "entrepreneuriat.plan.market.desc": "Analysez votre cible",
    "entrepreneuriat.plan.financial": "Plan financier",
    "entrepreneuriat.plan.financial.desc": "Projetez vos revenus",
    "entrepreneuriat.plan.cta": "Commencer mon business plan",
    // Pricing page
    "pricing.badge": "Plans",
    "pricing.title": "Nos",
    "pricing.title.highlight": "Plans",
    "pricing.description": "Choisissez le plan qui correspond à vos ambitions. Investissez dans votre avenir.",
    "pricing.nocard": "Aucune carte requise",
    "pricing.cancel": "Annulation gratuite",
    "pricing.support": "Support 24/7",
    "pricing.secure": "Paiement sécurisé",
    "pricing.faq.title": "Questions fréquentes",
    "pricing.faq.description": "Tout ce que vous devez savoir sur nos offres.",
    "pricing.faq.q1": "Puis-je changer de plan à tout moment ?",
    "pricing.faq.a1": "Oui, vous pouvez upgrader ou downgrader votre plan à tout moment. Les changements prennent effet immédiatement.",
    "pricing.faq.q2": "Y a-t-il un engagement minimum ?",
    "pricing.faq.a2": "Non, tous nos plans sont sans engagement. Vous pouvez annuler à tout moment sans frais.",
    "pricing.faq.q3": "Comment fonctionne l'essai gratuit ?",
    "pricing.faq.a3": "L'essai gratuit dure 7 jours. Vous pouvez tester toutes les fonctionnalités sans carte bancaire.",
    "pricing.faq.q4": "Quels moyens de paiement acceptez-vous ?",
    "pricing.faq.a4": "Nous acceptons les cartes bancaires marocaines et internationales, ainsi que les virements bancaires.",
    // Pricing plans
    "pricing.plan1.name": "Orientation Académique",
    "pricing.plan1.desc": "Pour les élèves et étudiants en quête de leur voie",
    "pricing.plan1.cta": "Commencer",
    "pricing.plan1.f1": "Tests d'orientation complets",
    "pricing.plan1.f2": "Parcours recommandés personnalisés",
    "pricing.plan1.f3": "Guide des filières au Maroc",
    "pricing.plan1.f4": "Ressources académiques",
    "pricing.plan1.f5": "Support par email",
    "pricing.plan2.name": "Stage & Travail",
    "pricing.plan2.desc": "Pour décrocher le stage ou l'emploi idéal",
    "pricing.plan2.cta": "Commencer",
    "pricing.plan2.f1": "Accès illimité aux offres de stage",
    "pricing.plan2.f2": "Modèles de CV professionnels",
    "pricing.plan2.f3": "Lettres de motivation personnalisées",
    "pricing.plan2.f4": "Coaching entretien",
    "pricing.plan2.f5": "Mise en relation entreprises",
    "pricing.plan2.f6": "Support prioritaire",
    "pricing.plan3.name": "Accompagnement Entrepreneurial",
    "pricing.plan3.desc": "Pour lancer et développer votre entreprise",
    "pricing.plan3.cta": "Commencer",
    "pricing.plan3.f1": "Guide création d'entreprise complet",
    "pricing.plan3.f2": "Templates business plan",
    "pricing.plan3.f3": "Étude de marché guidée",
    "pricing.plan3.f4": "Accès aux organismes de financement",
    "pricing.plan3.f5": "Coaching 1-to-1",
    "pricing.plan3.f6": "Relecture pitch deck",
    "pricing.plan3.f7": "Support dédié",
    // About page
    "about.badge": "À propos de NextStep",
    "about.title": "À propos de NextStep",
    "about.intro": "NextStep est une plateforme moderne dédiée à l'orientation, à l'intégration professionnelle et à l'accompagnement entrepreneurial. Dans un contexte où de nombreux jeunes au Maroc se retrouvent perdus face à leur avenir, notre mission est simple : transformer l'orientation en un véritable levier d'opportunités.",
    "about.context": "Chaque année, des milliers d'élèves choisissent une filière qui ne leur correspond pas, des étudiants abandonnent faute d'informations fiables, et des diplômés peinent à trouver un stage ou un emploi adapté. Ce constat a été le point de départ de la création de NextStep : offrir un espace clair, fiable et structuré pour guider chaque jeune, étape par étape.",
    "about.vision.title": "Notre vision",
    "about.vision.content": "Faire de l'orientation un outil stratégique permettant à chaque jeune de construire un futur solide, éclairé et aligné avec ses ambitions.",
    "about.mission.title": "Notre mission",
    "about.mission.intro": "Accompagner les jeunes dans leurs parcours :",
    "about.mission.point1.title": "Orientation académique :",
    "about.mission.point1.desc": "tests fiables et parcours recommandés.",
    "about.mission.point2.title": "Intégration professionnelle :",
    "about.mission.point2.desc": "offres de stages, modèles de CV, coaching.",
    "about.mission.point3.title": "Accompagnement entrepreneurial :",
    "about.mission.point3.desc": "guides étape par étape, outils d'étude de marché, accès aux organismes de financement.",
    "about.why.title": "Pourquoi nous avons créé NextStep ?",
    "about.why.intro": "Parce que les jeunes manquent souvent :",
    "about.why.point1": "d'informations centralisées et compréhensibles,",
    "about.why.point2": "d'un accompagnement personnalisé,",
    "about.why.point3": "d'un plan clair pour avancer.",
    "about.why.conclusion": "Notre objectif est de simplifier la prise de décision, de réduire la confusion et d'aider chaque jeune à avancer avec confiance.",
    "about.value.title": "Notre valeur ajoutée",
    "about.value.intro": "NextStep apporte :",
    "about.value.point1": "un outil simple, moderne et intuitif,",
    "about.value.point2": "un accompagnement expert et personnalisé,",
    "about.value.point3": "un accès direct aux possibilités académiques, professionnelles et entrepreneuriales,",
    "about.value.point4": "un parcours guidé pour évoluer étape par étape.",
    "about.slogan": "Build your future",
    "about.closing": "Grâce à une identité visuelle forte, un slogan inspirant et une approche centrée sur l'utilisateur, NextStep se positionne comme la plateforme incontournable pour avancer vers un avenir maîtrisé.",
    // Login page
    "login.title": "Bon retour !",
    "login.subtitle": "Connectez-vous pour continuer votre parcours.",
    "login.google": "Continuer avec Google",
    "login.or": "ou",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.forgot": "Mot de passe oublié ?",
    "login.submit": "Se connecter",
    "login.noAccount": "Pas encore de compte ?",
    "login.register": "S'inscrire gratuitement",
    "login.welcome": "Bienvenue sur NEXT STEP",
    "login.welcomeDesc": "La plateforme qui vous accompagne vers votre réussite professionnelle au Maroc.",
    // Register page
    "register.title": "Créer un compte",
    "register.subtitle": "Commencez votre parcours vers la réussite.",
    "register.google": "S'inscrire avec Google",
    "register.or": "ou",
    "register.name": "Nom complet",
    "register.email": "Email",
    "register.password": "Mot de passe (min. 8 caractères)",
    "register.terms": "En vous inscrivant, vous acceptez nos",
    "register.termsLink": "Conditions d'utilisation",
    "register.and": "et notre",
    "register.privacyLink": "Politique de confidentialité",
    "register.submit": "Créer mon compte",
    "register.hasAccount": "Déjà un compte ?",
    "register.login": "Se connecter",
    "register.heroTitle": "Construisez votre avenir avec",
    "register.heroDesc": "Rejoignez des milliers de Marocains qui ont déjà pris leur avenir en main.",
    "register.benefit1": "Tests d'orientation personnalisés",
    "register.benefit2": "Accès aux offres de stages",
    "register.benefit3": "Guides entrepreneuriat complets",
    "register.benefit4": "Ressources CV et entretien",
    // Orientation additional
    "orientation.level.beginner": "Débutant",
    "orientation.level.intermediate": "Intermédiaire",
    "orientation.path.marketing.desc": "Maîtrisez les fondamentaux du marketing numérique.",
    "orientation.path.dev.desc": "Devenez développeur web full-stack.",
    "orientation.path.project.desc": "Apprenez à gérer des projets avec agilité.",
    // Entrepreneuriat additional
    "entrepreneuriat.statut.auto.desc": "Idéal pour démarrer seul avec peu de formalités",
    "entrepreneuriat.statut.auto.adv1": "Pas de capital minimum",
    "entrepreneuriat.statut.auto.adv2": "Comptabilité simplifiée",
    "entrepreneuriat.statut.auto.adv3": "Charges réduites",
    "entrepreneuriat.statut.auto.best": "Freelances, consultants, petits commerces",
    "entrepreneuriat.statut.sarl.desc": "Structure classique pour les PME",
    "entrepreneuriat.statut.sarl.adv1": "Responsabilité limitée",
    "entrepreneuriat.statut.sarl.adv2": "Crédibilité accrue",
    "entrepreneuriat.statut.sarl.adv3": "Partenaires possibles",
    "entrepreneuriat.statut.sarl.best": "PME, projets à croissance modérée",
    "entrepreneuriat.statut.sa.desc": "Pour les projets ambitieux",
    "entrepreneuriat.statut.sa.adv1": "Levée de fonds facilitée",
    "entrepreneuriat.statut.sa.adv2": "Image professionnelle",
    "entrepreneuriat.statut.sa.adv3": "Cotation possible",
    "entrepreneuriat.statut.sa.best": "Startups, grands projets, levées de fonds",
    // Blog page
    "blog.badge": "Actualités & Conseils",
    "blog.page.title": "Actualités &",
    "blog.page.title.highlight": "Conseils",
    "blog.title": "Conseils et",
    "blog.title.highlight": "inspirations",
    "blog.description": "Articles, guides et témoignages pour vous accompagner dans votre parcours.",
    "blog.category.all": "Tous",
    "blog.category.orientation": "Orientation",
    "blog.category.stages": "Stages & Emploi",
    "blog.category.entrepreneuriat": "Entrepreneuriat",
    "blog.category.career": "Carrière",
    "blog.featured.title": "Comment réussir sa reconversion professionnelle au Maroc en 2024",
    "blog.featured.excerpt": "Guide complet pour changer de carrière avec succès. Découvrez les étapes clés, les erreurs à éviter et les opportunités du marché marocain.",
    "blog.featured.author": "Équipe NEXT STEP",
    "blog.featured.date": "5 Décembre 2024",
    "blog.featured.readTime": "8 min",
    "blog.readTime": "de lecture",
    "blog.readArticle": "Lire l'article",
    "blog.latestArticles": "Derniers articles",
    "blog.loadMore": "Charger plus d'articles",
    "blog.post1.title": "Top 10 des secteurs qui recrutent des stagiaires",
    "blog.post1.excerpt": "Découvrez les domaines les plus porteurs pour décrocher votre stage.",
    "blog.post1.date": "3 Décembre 2024",
    "blog.post2.title": "Créer son entreprise : les erreurs à éviter",
    "blog.post2.excerpt": "Les pièges classiques des jeunes entrepreneurs et comment les contourner.",
    "blog.post2.date": "1 Décembre 2024",
    "blog.post3.title": "Rédiger un CV qui se démarque",
    "blog.post3.excerpt": "Conseils pratiques pour créer un CV percutant adapté au marché marocain.",
    "blog.post3.date": "28 Novembre 2024",
    "blog.post4.title": "Les soft skills les plus recherchées en 2024",
    "blog.post4.excerpt": "Quelles compétences comportementales développer pour booster votre carrière.",
    "blog.post4.date": "25 Novembre 2024",
    "blog.post5.title": "Financer sa startup : guide complet",
    "blog.post5.excerpt": "Toutes les options de financement disponibles pour les entrepreneurs marocains.",
    "blog.post5.date": "22 Novembre 2024",
    "blog.newsletter.title": "Restez informé",
    "blog.newsletter.description": "Recevez nos meilleurs conseils et actualités directement dans votre boîte mail.",
    "blog.newsletter.placeholder": "Votre email",
    "blog.newsletter.subscribe": "S'abonner",
    // FAQ page
    "faq.badge": "Questions fréquentes",
    "faq.title": "Questions",
    "faq.title.highlight": "Fréquentes",
    "faq.description": "Trouvez les réponses à vos questions les plus courantes sur NEXT STEP.",
    "faq.q1": "Qu'est-ce que NEXT STEP ?",
    "faq.a1": "NEXT STEP est une plateforme complète dédiée à l'orientation académique, l'intégration professionnelle et l'accompagnement entrepreneurial au Maroc. Nous aidons les jeunes à construire leur avenir avec confiance.",
    "faq.q2": "Comment fonctionne le test d'orientation ?",
    "faq.a2": "Notre test d'orientation est basé sur des méthodes psychométriques validées. Il analyse vos intérêts, compétences et valeurs pour vous recommander les parcours les plus adaptés à votre profil.",
    "faq.q3": "Les offres de stage sont-elles vérifiées ?",
    "faq.a3": "Oui, toutes les offres de stage et d'emploi publiées sur NEXT STEP sont vérifiées par notre équipe pour garantir leur authenticité et leur qualité.",
    "faq.q4": "Comment puis-je accéder aux ressources premium ?",
    "faq.a4": "Les ressources premium sont accessibles via nos différents plans. Choisissez le plan qui correspond à vos besoins pour débloquer l'accès aux modèles de CV, lettres de motivation et coaching personnalisé.",
    "faq.q5": "Proposez-vous un accompagnement pour créer une entreprise ?",
    "faq.a5": "Absolument ! Notre plan Accompagnement Entrepreneurial inclut des guides complets, des templates de business plan, l'accès aux organismes de financement marocains et un coaching personnalisé.",
    "faq.q6": "Puis-je annuler mon abonnement à tout moment ?",
    "faq.a6": "Oui, tous nos plans sont sans engagement. Vous pouvez annuler à tout moment sans frais additionnels.",
    "faq.q7": "Comment contacter le support ?",
    "faq.a7": "Vous pouvez nous contacter par email à contact@nextstep.ma. Notre équipe répond généralement sous 24 heures.",
    "faq.q8": "NEXT STEP est-il disponible en plusieurs langues ?",
    "faq.a8": "Oui, NEXT STEP est disponible en français, anglais et arabe pour mieux servir notre communauté diversifiée au Maroc.",
    "faq.contact.text": "Vous n'avez pas trouvé la réponse à votre question ? Contactez-nous :",
  },
  en: {
    // Navbar
    "nav.orientation": "Career Guidance",
    "nav.stages": "Internships",
    "nav.entrepreneuriat": "Entrepreneurship",
    "nav.pricing": "Plans",
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.login": "Sign in",
    "nav.register": "Get started free",
    "nav.slogan": "Build your future",
    // Hero
    "hero.badge": "Morocco's #1 Career Platform",
    "hero.title": "Build",
    "hero.title.highlight": "your",
    "hero.title.end": "future",
    "hero.description": "Career guidance, internships, and entrepreneurship all in one platform. Build your professional path with confidence and clarity.",
    "hero.cta.orientation": "Start my orientation",
    "hero.cta.stages": "Explore internships",
    "hero.card.orientation": "Career Guidance",
    "hero.card.orientation.desc": "Interactive tests and personalized roadmaps to find your path.",
    "hero.card.stagesjobs": "Internships & Jobs",
    "hero.card.stagesjobs.desc": "Targeted internship and job offers with resources to land your ideal position.",
    "hero.card.business": "Entrepreneurship",
    "hero.card.business.desc": "Complete guides to create and launch your business in Morocco.",
    "hero.stats.users": "Active users",
    "hero.stats.offers": "Internship offers",
    "hero.stats.satisfaction": "Satisfaction rate",
    "hero.stats.partners": "Partners",
    // Features
    "features.badge": "Features",
    "features.title": "Everything you need to",
    "features.title.highlight": "succeed",
    "features.description": "A complete platform that supports you at every step of your professional journey.",
    "features.orientation.title": "Smart orientation tests",
    "features.orientation.desc": "Discover your talents and aspirations through our interactive tests based on work psychology.",
    "features.coaching.title": "Personalized coaching",
    "features.coaching.desc": "Get customized support from our career and orientation experts.",
    "features.roadmap.title": "Career roadmaps",
    "features.roadmap.desc": "Visualize your journey with detailed step-by-step action plans.",
    "features.resources.title": "Premium resources",
    "features.resources.desc": "Access CV templates, cover letters, and professional guides.",
    "features.certifications.title": "Recognized certifications",
    "features.certifications.desc": "Validate your skills with certifications valued by employers.",
    "features.progress.title": "Progress tracking",
    "features.progress.desc": "Track your advancement and celebrate each step of your journey.",
    // Testimonials
    "testimonials.badge": "Testimonials",
    "testimonials.title": "They transformed their",
    "testimonials.title.highlight": "future",
    "testimonials.description": "Discover success stories from our community.",
    // CTA
    "cta.badge": "Ready to take the leap?",
    "cta.title": "Start your transformation",
    "cta.title.highlight": "today",
    "cta.description": "Join thousands of Moroccans who have already taken control of their future. Free registration, guaranteed results.",
    "cta.button": "Create my free account",
    "cta.button.secondary": "View offers",
    "cta.note": "No credit card required • Cancel anytime",
    // Footer
    "footer.description": "The all-in-one platform for career guidance, internships, job offers and entrepreneurship in Morocco. Build your future with confidence.",
    "footer.platform": "Platform",
    "footer.resources": "Resources",
    "footer.stages": "Internships",
    "footer.jobs": "Job Offers",
    "footer.blog": "News & Tips",
    "footer.faq": "FAQ",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.rights": "All rights reserved.",
    // Orientation page
    "orientation.badge": "Career guidance",
    "orientation.title": "Find your",
    "orientation.title.highlight": "path",
    "orientation.description": "Interactive tests, recommended paths and personalized roadmaps to build your professional future.",
    "orientation.cta": "Start the test",
    "orientation.test.badge": "Quick test",
    "orientation.test.title": "Discover your profile",
    "orientation.test.description": "Answer a few questions to discover the paths that suit you.",
    "orientation.test.question": "Question",
    "orientation.test.q1": "Do you like solving complex problems?",
    "orientation.test.q2": "Do you prefer working in a team or alone?",
    "orientation.test.q3": "Are you comfortable with new technologies?",
    "orientation.test.a1": "Not at all",
    "orientation.test.a2": "Sometimes",
    "orientation.test.a3": "Absolutely",
    "orientation.test.complete": "Test completed!",
    "orientation.test.complete.desc": "Based on your answers, here are the paths that suit you best.",
    "orientation.test.results": "View results",
    "orientation.paths.badge": "Recommended paths",
    "orientation.paths.title": "Explore opportunities",
    "orientation.paths.description": "Structured paths to guide you to success.",
    "orientation.paths.view": "View path",
    "orientation.roadmap.badge": "Interactive roadmap",
    "orientation.roadmap.title": "Visualize your journey",
    "orientation.roadmap.title.highlight": "step by step",
    "orientation.roadmap.description": "Our roadmap tool allows you to track your progress, plan your goals and celebrate each achievement.",
    "orientation.roadmap.f1": "Clear and measurable goals",
    "orientation.roadmap.f2": "Real-time progress tracking",
    "orientation.roadmap.f3": "Resources adapted to each step",
    "orientation.roadmap.cta": "Create my roadmap",
    "orientation.roadmap.step1": "Define your goals",
    "orientation.roadmap.step2": "Follow a training",
    "orientation.roadmap.step3": "Get an internship",
    "orientation.roadmap.step4": "Land a job",
    // Stages page
    "stages.badge": "Internship offers",
    "stages.title": "Find the ideal",
    "stages.title.highlight": "internship",
    "stages.description": "Hundreds of internship opportunities in Morocco. Filter by city, field and level to find the one that suits you.",
    "stages.search": "Search for an internship, a company...",
    "stages.all.cities": "All",
    "stages.all.domains": "All",
    "stages.offers.found": "offers found",
    "stages.more.filters": "More filters",
    "stages.apply": "Apply",
    "stages.learn.more": "Learn more",
    "stages.resources": "Resources",
    "stages.resources.cv": "CV Templates",
    "stages.resources.cv.desc": "Professional templates adapted to the Moroccan market",
    "stages.resources.letter": "Cover letters",
    "stages.resources.letter.desc": "Examples by sector and education level",
    "stages.resources.interview": "Interview preparation",
    "stages.resources.interview.desc": "Videos and tips to ace your interviews",
    "stages.tip.title": "Tip of the day",
    "stages.tip.content": "Personalize each application! Adapt your CV and cover letter to multiply your chances by 3.",
    "stages.tip.more": "More tips",
    "stages.posted": "Posted",
    "stages.days": "days ago",
    "stages.week": "1 week ago",
    // Entrepreneuriat page
    "entrepreneuriat.badge": "Entrepreneurship in Morocco",
    "entrepreneuriat.title": "Launch your",
    "entrepreneuriat.title.highlight": "business",
    "entrepreneuriat.description": "Complete guide to create and develop your business in Morocco. Legal statuses, administrative procedures, financing.",
    "entrepreneuriat.cta.guide": "Start the guide",
    "entrepreneuriat.cta.plan": "Create my business plan",
    "entrepreneuriat.steps.badge": "Key steps",
    "entrepreneuriat.steps.title": "Create your business in",
    "entrepreneuriat.steps.title.highlight": "4 steps",
    "entrepreneuriat.steps.description": "A structured path to turn your idea into reality.",
    "entrepreneuriat.step1.title": "Define your project",
    "entrepreneuriat.step1.desc": "Clarify your idea, identify your target market and validate your concept.",
    "entrepreneuriat.step2.title": "Choose legal status",
    "entrepreneuriat.step2.desc": "SARL, SA, auto-entrepreneur... Discover which status suits your activity.",
    "entrepreneuriat.step3.title": "Administrative formalities",
    "entrepreneuriat.step3.desc": "Trade register, CRI, CNSS... All procedures explained simply.",
    "entrepreneuriat.step4.title": "Find financing",
    "entrepreneuriat.step4.desc": "INDH, ANAPEC, banks, investors... Explore all options.",
    "entrepreneuriat.statuts.badge": "Legal statuses",
    "entrepreneuriat.statuts.title": "Choose the right status",
    "entrepreneuriat.statuts.description": "Compare different legal forms to find the one that suits you.",
    "entrepreneuriat.statuts.ideal": "Ideal for:",
    "entrepreneuriat.financing.badge": "Financing",
    "entrepreneuriat.financing.title": "Find the right",
    "entrepreneuriat.financing.title.highlight": "financing",
    "entrepreneuriat.financing.title.end": "options",
    "entrepreneuriat.financing.description": "Morocco offers many financing opportunities for entrepreneurs. Discover the programs that match your project.",
    "entrepreneuriat.stats.title": "Did you know?",
    "entrepreneuriat.stats.1": "businesses created in 5 years in Morocco",
    "entrepreneuriat.stats.2": "active auto-entrepreneurs",
    "entrepreneuriat.stats.3": "incubators and accelerators",
    "entrepreneuriat.plan.badge": "Free tool",
    "entrepreneuriat.plan.title": "Create your",
    "entrepreneuriat.plan.title.highlight": "Business Plan",
    "entrepreneuriat.plan.description": "Our simplified tool guides you step by step to create a professional and convincing business plan.",
    "entrepreneuriat.plan.summary": "Executive summary",
    "entrepreneuriat.plan.summary.desc": "Present your vision",
    "entrepreneuriat.plan.market": "Market study",
    "entrepreneuriat.plan.market.desc": "Analyze your target",
    "entrepreneuriat.plan.financial": "Financial plan",
    "entrepreneuriat.plan.financial.desc": "Project your revenues",
    "entrepreneuriat.plan.cta": "Start my business plan",
    // Pricing page
    "pricing.badge": "Plans",
    "pricing.title": "Our",
    "pricing.title.highlight": "Plans",
    "pricing.description": "Choose the plan that matches your ambitions. Invest in your future.",
    "pricing.nocard": "No card required",
    "pricing.cancel": "Free cancellation",
    "pricing.support": "24/7 support",
    "pricing.secure": "Secure payment",
    "pricing.faq.title": "Frequently asked questions",
    "pricing.faq.description": "Everything you need to know about our offers.",
    "pricing.faq.q1": "Can I change plans anytime?",
    "pricing.faq.a1": "Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately.",
    "pricing.faq.q2": "Is there a minimum commitment?",
    "pricing.faq.a2": "No, all our plans are commitment-free. You can cancel anytime without fees.",
    "pricing.faq.q3": "How does the free trial work?",
    "pricing.faq.a3": "The free trial lasts 7 days. You can test all features without a credit card.",
    "pricing.faq.q4": "What payment methods do you accept?",
    "pricing.faq.a4": "We accept Moroccan and international bank cards, as well as bank transfers.",
    // Pricing plans
    "pricing.plan1.name": "Academic Orientation",
    "pricing.plan1.desc": "For students seeking their path",
    "pricing.plan1.cta": "Get Started",
    "pricing.plan1.f1": "Complete orientation tests",
    "pricing.plan1.f2": "Personalized recommended paths",
    "pricing.plan1.f3": "Guide to programs in Morocco",
    "pricing.plan1.f4": "Academic resources",
    "pricing.plan1.f5": "Email support",
    "pricing.plan2.name": "Internship & Work",
    "pricing.plan2.desc": "To land the ideal internship or job",
    "pricing.plan2.cta": "Get Started",
    "pricing.plan2.f1": "Unlimited access to internship offers",
    "pricing.plan2.f2": "Professional CV templates",
    "pricing.plan2.f3": "Personalized cover letters",
    "pricing.plan2.f4": "Interview coaching",
    "pricing.plan2.f5": "Company connections",
    "pricing.plan2.f6": "Priority support",
    "pricing.plan3.name": "Entrepreneurial Support",
    "pricing.plan3.desc": "To launch and grow your business",
    "pricing.plan3.cta": "Get Started",
    "pricing.plan3.f1": "Complete business creation guide",
    "pricing.plan3.f2": "Business plan templates",
    "pricing.plan3.f3": "Guided market research",
    "pricing.plan3.f4": "Access to funding organizations",
    "pricing.plan3.f5": "1-on-1 coaching",
    "pricing.plan3.f6": "Pitch deck review",
    "pricing.plan3.f7": "Dedicated support",
    // About page
    "about.badge": "About NextStep",
    "about.title": "About NextStep",
    "about.intro": "NextStep is a modern platform dedicated to career guidance, professional integration, and entrepreneurial support. In a context where many young people in Morocco find themselves lost facing their future, our mission is simple: transform orientation into a real lever of opportunities.",
    "about.context": "Every year, thousands of students choose a field that doesn't suit them, students drop out due to lack of reliable information, and graduates struggle to find a suitable internship or job. This observation was the starting point for creating NextStep: to offer a clear, reliable, and structured space to guide every young person, step by step.",
    "about.vision.title": "Our Vision",
    "about.vision.content": "To make orientation a strategic tool allowing every young person to build a solid future, enlightened and aligned with their ambitions.",
    "about.mission.title": "Our Mission",
    "about.mission.intro": "Supporting young people in their journey:",
    "about.mission.point1.title": "Academic orientation:",
    "about.mission.point1.desc": "reliable tests and recommended paths.",
    "about.mission.point2.title": "Professional integration:",
    "about.mission.point2.desc": "internship offers, CV templates, coaching.",
    "about.mission.point3.title": "Entrepreneurial support:",
    "about.mission.point3.desc": "step-by-step guides, market research tools, access to funding organizations.",
    "about.why.title": "Why We Created NextStep?",
    "about.why.intro": "Because young people often lack:",
    "about.why.point1": "centralized and understandable information,",
    "about.why.point2": "personalized support,",
    "about.why.point3": "a clear plan to move forward.",
    "about.why.conclusion": "Our goal is to simplify decision-making, reduce confusion, and help every young person move forward with confidence.",
    "about.value.title": "Our Added Value",
    "about.value.intro": "NextStep brings:",
    "about.value.point1": "a simple, modern and intuitive tool,",
    "about.value.point2": "expert and personalized support,",
    "about.value.point3": "direct access to academic, professional and entrepreneurial opportunities,",
    "about.value.point4": "a guided journey to evolve step by step.",
    "about.slogan": "Build your future",
    "about.closing": "With a strong visual identity, an inspiring slogan, and a user-centered approach, NextStep positions itself as the essential platform for moving towards a mastered future.",
    // Login page
    "login.title": "Welcome back!",
    "login.subtitle": "Sign in to continue your journey.",
    "login.google": "Continue with Google",
    "login.or": "or",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgot": "Forgot password?",
    "login.submit": "Sign in",
    "login.noAccount": "Don't have an account?",
    "login.register": "Sign up for free",
    "login.welcome": "Welcome to NEXT STEP",
    "login.welcomeDesc": "The platform that guides you towards professional success in Morocco.",
    // Register page
    "register.title": "Create an account",
    "register.subtitle": "Start your journey to success.",
    "register.google": "Sign up with Google",
    "register.or": "or",
    "register.name": "Full name",
    "register.email": "Email",
    "register.password": "Password (min. 8 characters)",
    "register.terms": "By signing up, you accept our",
    "register.termsLink": "Terms of Service",
    "register.and": "and our",
    "register.privacyLink": "Privacy Policy",
    "register.submit": "Create my account",
    "register.hasAccount": "Already have an account?",
    "register.login": "Sign in",
    "register.heroTitle": "Build your future with",
    "register.heroDesc": "Join thousands of Moroccans who have already taken control of their future.",
    "register.benefit1": "Personalized orientation tests",
    "register.benefit2": "Access to internship offers",
    "register.benefit3": "Complete entrepreneurship guides",
    "register.benefit4": "CV and interview resources",
    // Orientation additional
    "orientation.level.beginner": "Beginner",
    "orientation.level.intermediate": "Intermediate",
    "orientation.path.marketing.desc": "Master the fundamentals of digital marketing.",
    "orientation.path.dev.desc": "Become a full-stack web developer.",
    "orientation.path.project.desc": "Learn to manage projects with agility.",
    // Entrepreneuriat additional
    "entrepreneuriat.statut.auto.desc": "Ideal for starting alone with few formalities",
    "entrepreneuriat.statut.auto.adv1": "No minimum capital",
    "entrepreneuriat.statut.auto.adv2": "Simplified accounting",
    "entrepreneuriat.statut.auto.adv3": "Reduced charges",
    "entrepreneuriat.statut.auto.best": "Freelancers, consultants, small businesses",
    "entrepreneuriat.statut.sarl.desc": "Classic structure for SMEs",
    "entrepreneuriat.statut.sarl.adv1": "Limited liability",
    "entrepreneuriat.statut.sarl.adv2": "Increased credibility",
    "entrepreneuriat.statut.sarl.adv3": "Partners possible",
    "entrepreneuriat.statut.sarl.best": "SMEs, moderate growth projects",
    "entrepreneuriat.statut.sa.desc": "For ambitious projects",
    "entrepreneuriat.statut.sa.adv1": "Easier fundraising",
    "entrepreneuriat.statut.sa.adv2": "Professional image",
    "entrepreneuriat.statut.sa.adv3": "IPO possible",
    "entrepreneuriat.statut.sa.best": "Startups, large projects, fundraising",
    // Blog page
    "blog.badge": "News & Tips",
    "blog.page.title": "News &",
    "blog.page.title.highlight": "Tips",
    "blog.title": "Tips and",
    "blog.title.highlight": "inspirations",
    "blog.description": "Articles, guides and testimonials to accompany you in your journey.",
    "blog.category.all": "All",
    "blog.category.orientation": "Orientation",
    "blog.category.stages": "Internships & Jobs",
    "blog.category.entrepreneuriat": "Entrepreneurship",
    "blog.category.career": "Career",
    "blog.featured.title": "How to successfully change careers in Morocco in 2024",
    "blog.featured.excerpt": "Complete guide to changing careers successfully. Discover key steps, mistakes to avoid and Moroccan market opportunities.",
    "blog.featured.author": "NEXT STEP Team",
    "blog.featured.date": "December 5, 2024",
    "blog.featured.readTime": "8 min",
    "blog.readTime": "read",
    "blog.readArticle": "Read article",
    "blog.latestArticles": "Latest articles",
    "blog.loadMore": "Load more articles",
    "blog.post1.title": "Top 10 sectors recruiting interns",
    "blog.post1.excerpt": "Discover the most promising fields to land your internship.",
    "blog.post1.date": "December 3, 2024",
    "blog.post2.title": "Starting a business: mistakes to avoid",
    "blog.post2.excerpt": "Classic traps for young entrepreneurs and how to avoid them.",
    "blog.post2.date": "December 1, 2024",
    "blog.post3.title": "Write a standout CV",
    "blog.post3.excerpt": "Practical tips to create a compelling CV adapted to the Moroccan market.",
    "blog.post3.date": "November 28, 2024",
    "blog.post4.title": "Most sought-after soft skills in 2024",
    "blog.post4.excerpt": "Which behavioral skills to develop to boost your career.",
    "blog.post4.date": "November 25, 2024",
    "blog.post5.title": "Financing your startup: complete guide",
    "blog.post5.excerpt": "All financing options available for Moroccan entrepreneurs.",
    "blog.post5.date": "November 22, 2024",
    "blog.newsletter.title": "Stay informed",
    "blog.newsletter.description": "Receive our best tips and news directly in your inbox.",
    "blog.newsletter.placeholder": "Your email",
    "blog.newsletter.subscribe": "Subscribe",
    // FAQ page
    "faq.badge": "Frequently Asked Questions",
    "faq.title": "Frequently Asked",
    "faq.title.highlight": "Questions",
    "faq.description": "Find answers to your most common questions about NEXT STEP.",
    "faq.q1": "What is NEXT STEP?",
    "faq.a1": "NEXT STEP is a comprehensive platform dedicated to academic orientation, professional integration and entrepreneurial support in Morocco. We help young people build their future with confidence.",
    "faq.q2": "How does the orientation test work?",
    "faq.a2": "Our orientation test is based on validated psychometric methods. It analyzes your interests, skills and values to recommend the most suitable paths for your profile.",
    "faq.q3": "Are internship offers verified?",
    "faq.a3": "Yes, all internship and job offers published on NEXT STEP are verified by our team to guarantee their authenticity and quality.",
    "faq.q4": "How can I access premium resources?",
    "faq.a4": "Premium resources are accessible through our different plans. Choose the plan that suits your needs to unlock access to CV templates, cover letters and personalized coaching.",
    "faq.q5": "Do you offer support for starting a business?",
    "faq.a5": "Absolutely! Our Entrepreneurial Support plan includes complete guides, business plan templates, access to Moroccan funding organizations and personalized coaching.",
    "faq.q6": "Can I cancel my subscription at any time?",
    "faq.a6": "Yes, all our plans are commitment-free. You can cancel at any time without additional fees.",
    "faq.q7": "How to contact support?",
    "faq.a7": "You can contact us by email at contact@nextstep.ma. Our team usually responds within 24 hours.",
    "faq.q8": "Is NEXT STEP available in multiple languages?",
    "faq.a8": "Yes, NEXT STEP is available in French, English and Arabic to better serve our diverse community in Morocco.",
    "faq.contact.text": "Didn't find the answer to your question? Contact us:",
  },
  ar: {
    // Navbar
    "nav.orientation": "التوجيه المهني",
    "nav.stages": "التدريب",
    "nav.entrepreneuriat": "ريادة الأعمال",
    "nav.pricing": "الخطط",
    "nav.about": "من نحن",
    "nav.blog": "المدونة",
    "nav.login": "تسجيل الدخول",
    "nav.register": "ابدأ مجاناً",
    "nav.slogan": "Build your future",
    // Hero
    "hero.badge": "المنصة الأولى للتوجيه في المغرب",
    "hero.title": "Build",
    "hero.title.highlight": "your",
    "hero.title.end": "future",
    "hero.description": "التوجيه المهني والتدريب وريادة الأعمال في منصة واحدة. ابنِ مسارك المهني بثقة ووضوح.",
    "hero.cta.orientation": "ابدأ توجيهي",
    "hero.cta.stages": "استكشف التدريبات",
    "hero.card.orientation": "التوجيه المهني",
    "hero.card.orientation.desc": "اختبارات تفاعلية وخطط مخصصة لإيجاد طريقك.",
    "hero.card.stagesjobs": "التدريب وفرص العمل",
    "hero.card.stagesjobs.desc": "عروض تدريب وتوظيف مستهدفة وموارد للحصول على الوظيفة المثالية.",
    "hero.card.business": "ريادة الأعمال",
    "hero.card.business.desc": "أدلة شاملة لإنشاء وإطلاق مشروعك في المغرب.",
    "hero.stats.users": "مستخدم نشط",
    "hero.stats.offers": "عرض تدريب",
    "hero.stats.satisfaction": "معدل الرضا",
    "hero.stats.partners": "شريك",
    // Features
    "features.badge": "المميزات",
    "features.title": "كل ما تحتاجه لتحقيق",
    "features.title.highlight": "النجاح",
    "features.description": "منصة متكاملة ترافقك في كل خطوة من مسارك المهني.",
    "features.orientation.title": "اختبارات توجيه ذكية",
    "features.orientation.desc": "اكتشف مواهبك وتطلعاتك من خلال اختباراتنا التفاعلية.",
    "features.coaching.title": "تدريب شخصي",
    "features.coaching.desc": "احصل على دعم مخصص من خبرائنا في التوجيه والمهنة.",
    "features.roadmap.title": "خرائط طريق مهنية",
    "features.roadmap.desc": "تصور رحلتك بخطط عمل مفصلة خطوة بخطوة.",
    "features.resources.title": "موارد متميزة",
    "features.resources.desc": "الوصول إلى قوالب السيرة الذاتية ورسائل التقديم.",
    "features.certifications.title": "شهادات معترف بها",
    "features.certifications.desc": "صادق على مهاراتك بشهادات يقدرها أصحاب العمل.",
    "features.progress.title": "تتبع التقدم",
    "features.progress.desc": "تابع تقدمك واحتفل بكل خطوة من رحلتك.",
    // Testimonials
    "testimonials.badge": "شهادات",
    "testimonials.title": "لقد غيروا",
    "testimonials.title.highlight": "مستقبلهم",
    "testimonials.description": "اكتشف قصص نجاح مجتمعنا.",
    // CTA
    "cta.badge": "مستعد للانطلاق؟",
    "cta.title": "ابدأ تحولك",
    "cta.title.highlight": "اليوم",
    "cta.description": "انضم إلى آلاف المغاربة الذين تحكموا في مستقبلهم. تسجيل مجاني، نتائج مضمونة.",
    "cta.button": "إنشاء حسابي المجاني",
    "cta.button.secondary": "عرض العروض",
    "cta.note": "لا حاجة لبطاقة ائتمان • إلغاء في أي وقت",
    // Footer
    "footer.description": "المنصة الشاملة للتوجيه والتدريب وفرص العمل وريادة الأعمال في المغرب. ابنِ مستقبلك بثقة.",
    "footer.platform": "المنصة",
    "footer.resources": "الموارد",
    "footer.stages": "التدريب",
    "footer.jobs": "فرص العمل",
    "footer.blog": "أخبار ونصائح",
    "footer.faq": "الأسئلة الشائعة",
    "footer.company": "الشركة",
    "footer.contact": "اتصل بنا",
    "footer.legal": "قانوني",
    "footer.rights": "جميع الحقوق محفوظة.",
    // Orientation page
    "orientation.badge": "التوجيه المهني",
    "orientation.title": "اعثر على",
    "orientation.title.highlight": "طريقك",
    "orientation.description": "اختبارات تفاعلية ومسارات موصى بها وخرائط طريق مخصصة لبناء مستقبلك المهني.",
    "orientation.cta": "ابدأ الاختبار",
    "orientation.test.badge": "اختبار سريع",
    "orientation.test.title": "اكتشف ملفك الشخصي",
    "orientation.test.description": "أجب على بعض الأسئلة لاكتشاف المسارات المناسبة لك.",
    "orientation.test.question": "سؤال",
    "orientation.test.q1": "هل تحب حل المشاكل المعقدة؟",
    "orientation.test.q2": "هل تفضل العمل في فريق أم بمفردك؟",
    "orientation.test.q3": "هل أنت مرتاح مع التقنيات الجديدة؟",
    "orientation.test.a1": "ليس على الإطلاق",
    "orientation.test.a2": "أحياناً",
    "orientation.test.a3": "بالتأكيد",
    "orientation.test.complete": "تم الاختبار!",
    "orientation.test.complete.desc": "بناءً على إجاباتك، إليك المسارات الأنسب لك.",
    "orientation.test.results": "عرض النتائج",
    "orientation.paths.badge": "مسارات موصى بها",
    "orientation.paths.title": "استكشف الفرص",
    "orientation.paths.description": "مسارات منظمة لتوجيهك نحو النجاح.",
    "orientation.paths.view": "عرض المسار",
    "orientation.roadmap.badge": "خريطة طريق تفاعلية",
    "orientation.roadmap.title": "تصور رحلتك",
    "orientation.roadmap.title.highlight": "خطوة بخطوة",
    "orientation.roadmap.description": "تتيح لك أداة خريطة الطريق تتبع تقدمك والتخطيط لأهدافك والاحتفال بكل إنجاز.",
    "orientation.roadmap.f1": "أهداف واضحة وقابلة للقياس",
    "orientation.roadmap.f2": "تتبع التقدم في الوقت الفعلي",
    "orientation.roadmap.f3": "موارد مكيفة لكل خطوة",
    "orientation.roadmap.cta": "إنشاء خريطتي",
    "orientation.roadmap.step1": "حدد أهدافك",
    "orientation.roadmap.step2": "اتبع تدريباً",
    "orientation.roadmap.step3": "احصل على تدريب",
    "orientation.roadmap.step4": "احصل على وظيفة",
    // Stages page
    "stages.badge": "عروض التدريب",
    "stages.title": "اعثر على التدريب",
    "stages.title.highlight": "المثالي",
    "stages.description": "مئات فرص التدريب في المغرب. قم بالتصفية حسب المدينة والمجال والمستوى.",
    "stages.search": "ابحث عن تدريب، شركة...",
    "stages.all.cities": "الكل",
    "stages.all.domains": "الكل",
    "stages.offers.found": "عروض موجودة",
    "stages.more.filters": "المزيد من الفلاتر",
    "stages.apply": "تقدم",
    "stages.learn.more": "اعرف المزيد",
    "stages.resources": "الموارد",
    "stages.resources.cv": "قوالب السيرة الذاتية",
    "stages.resources.cv.desc": "قوالب احترافية مكيفة للسوق المغربي",
    "stages.resources.letter": "رسائل التقديم",
    "stages.resources.letter.desc": "أمثلة حسب القطاع ومستوى التعليم",
    "stages.resources.interview": "التحضير للمقابلة",
    "stages.resources.interview.desc": "فيديوهات ونصائح لنجاح مقابلاتك",
    "stages.tip.title": "نصيحة اليوم",
    "stages.tip.content": "خصص كل طلب! قم بتكييف سيرتك الذاتية ورسالة التقديم لمضاعفة فرصك بمقدار 3.",
    "stages.tip.more": "المزيد من النصائح",
    "stages.posted": "منذ",
    "stages.days": "أيام",
    "stages.week": "أسبوع واحد",
    // Entrepreneuriat page
    "entrepreneuriat.badge": "ريادة الأعمال في المغرب",
    "entrepreneuriat.title": "أطلق",
    "entrepreneuriat.title.highlight": "مشروعك",
    "entrepreneuriat.description": "دليل شامل لإنشاء وتطوير عملك في المغرب. الأوضاع القانونية، الإجراءات الإدارية، التمويل.",
    "entrepreneuriat.cta.guide": "ابدأ الدليل",
    "entrepreneuriat.cta.plan": "إنشاء خطة عملي",
    "entrepreneuriat.steps.badge": "الخطوات الرئيسية",
    "entrepreneuriat.steps.title": "أنشئ مشروعك في",
    "entrepreneuriat.steps.title.highlight": "4 خطوات",
    "entrepreneuriat.steps.description": "مسار منظم لتحويل فكرتك إلى واقع.",
    "entrepreneuriat.step1.title": "حدد مشروعك",
    "entrepreneuriat.step1.desc": "وضح فكرتك، حدد سوقك المستهدف وتحقق من مفهومك.",
    "entrepreneuriat.step2.title": "اختر الوضع القانوني",
    "entrepreneuriat.step2.desc": "SARL، SA، المقاول الذاتي... اكتشف الوضع المناسب لنشاطك.",
    "entrepreneuriat.step3.title": "الإجراءات الإدارية",
    "entrepreneuriat.step3.desc": "السجل التجاري، CRI، CNSS... جميع الإجراءات موضحة ببساطة.",
    "entrepreneuriat.step4.title": "ابحث عن التمويل",
    "entrepreneuriat.step4.desc": "INDH، ANAPEC، البنوك، المستثمرون... استكشف جميع الخيارات.",
    "entrepreneuriat.statuts.badge": "الأوضاع القانونية",
    "entrepreneuriat.statuts.title": "اختر الوضع المناسب",
    "entrepreneuriat.statuts.description": "قارن بين الأشكال القانونية المختلفة للعثور على ما يناسبك.",
    "entrepreneuriat.statuts.ideal": "مثالي لـ:",
    "entrepreneuriat.financing.badge": "التمويل",
    "entrepreneuriat.financing.title": "اعثر على",
    "entrepreneuriat.financing.title.highlight": "التمويل",
    "entrepreneuriat.financing.title.end": "المناسب",
    "entrepreneuriat.financing.description": "يقدم المغرب العديد من فرص التمويل للمقاولين. اكتشف البرامج المناسبة لمشروعك.",
    "entrepreneuriat.stats.title": "هل تعلم؟",
    "entrepreneuriat.stats.1": "شركات أُنشئت في 5 سنوات في المغرب",
    "entrepreneuriat.stats.2": "مقاول ذاتي نشط",
    "entrepreneuriat.stats.3": "حاضنات ومسرعات",
    "entrepreneuriat.plan.badge": "أداة مجانية",
    "entrepreneuriat.plan.title": "أنشئ",
    "entrepreneuriat.plan.title.highlight": "خطة عملك",
    "entrepreneuriat.plan.description": "أداتنا المبسطة ترشدك خطوة بخطوة لإنشاء خطة عمل احترافية ومقنعة.",
    "entrepreneuriat.plan.summary": "الملخص التنفيذي",
    "entrepreneuriat.plan.summary.desc": "قدم رؤيتك",
    "entrepreneuriat.plan.market": "دراسة السوق",
    "entrepreneuriat.plan.market.desc": "حلل جمهورك المستهدف",
    "entrepreneuriat.plan.financial": "الخطة المالية",
    "entrepreneuriat.plan.financial.desc": "توقع إيراداتك",
    "entrepreneuriat.plan.cta": "ابدأ خطة عملي",
    // Pricing page
    "pricing.badge": "الخطط",
    "pricing.title": "اكتشف",
    "pricing.title.highlight": "خططنا",
    "pricing.description": "اختر الخطة التي تناسب طموحاتك. استثمر في مستقبلك.",
    "pricing.nocard": "لا حاجة لبطاقة",
    "pricing.cancel": "إلغاء مجاني",
    "pricing.support": "دعم 24/7",
    "pricing.secure": "دفع آمن",
    "pricing.faq.title": "الأسئلة الشائعة",
    "pricing.faq.description": "كل ما تحتاج معرفته عن عروضنا.",
    "pricing.faq.q1": "هل يمكنني تغيير الخطة في أي وقت؟",
    "pricing.faq.a1": "نعم، يمكنك الترقية أو الرجوع في أي وقت. التغييرات تطبق فوراً.",
    "pricing.faq.q2": "هل هناك التزام أدنى؟",
    "pricing.faq.a2": "لا، جميع خططنا بدون التزام. يمكنك الإلغاء في أي وقت بدون رسوم.",
    "pricing.faq.q3": "كيف تعمل التجربة المجانية؟",
    "pricing.faq.a3": "التجربة المجانية تدوم 7 أيام. يمكنك اختبار جميع الميزات بدون بطاقة ائتمان.",
    "pricing.faq.q4": "ما وسائل الدفع التي تقبلونها؟",
    "pricing.faq.a4": "نقبل البطاقات البنكية المغربية والدولية، وكذلك التحويلات البنكية.",
    // Pricing plans
    "pricing.plan1.name": "التوجيه الأكاديمي",
    "pricing.plan1.desc": "للطلاب الباحثين عن طريقهم",
    "pricing.plan1.cta": "ابدأ الآن",
    "pricing.plan1.f1": "اختبارات توجيه شاملة",
    "pricing.plan1.f2": "مسارات موصى بها مخصصة",
    "pricing.plan1.f3": "دليل التخصصات في المغرب",
    "pricing.plan1.f4": "موارد أكاديمية",
    "pricing.plan1.f5": "دعم بالبريد الإلكتروني",
    "pricing.plan2.name": "التدريب والعمل",
    "pricing.plan2.desc": "للحصول على التدريب أو الوظيفة المثالية",
    "pricing.plan2.cta": "ابدأ الآن",
    "pricing.plan2.f1": "وصول غير محدود لعروض التدريب",
    "pricing.plan2.f2": "قوالب سيرة ذاتية احترافية",
    "pricing.plan2.f3": "رسائل تقديم مخصصة",
    "pricing.plan2.f4": "تدريب على المقابلات",
    "pricing.plan2.f5": "ربط مع الشركات",
    "pricing.plan2.f6": "دعم أولوية",
    "pricing.plan3.name": "دعم ريادة الأعمال",
    "pricing.plan3.desc": "لإطلاق وتطوير مشروعك",
    "pricing.plan3.cta": "ابدأ الآن",
    "pricing.plan3.f1": "دليل إنشاء مشروع شامل",
    "pricing.plan3.f2": "قوالب خطة العمل",
    "pricing.plan3.f3": "دراسة سوق موجهة",
    "pricing.plan3.f4": "الوصول لمنظمات التمويل",
    "pricing.plan3.f5": "تدريب فردي",
    "pricing.plan3.f6": "مراجعة عرض المشروع",
    "pricing.plan3.f7": "دعم مخصص",
    // About page
    "about.badge": "من نحن",
    "about.title": "من نحن - NextStep",
    "about.intro": "NextStep هي منصة حديثة مخصصة للتوجيه والاندماج المهني ودعم ريادة الأعمال. في سياق حيث يجد العديد من الشباب في المغرب أنفسهم تائهين أمام مستقبلهم، مهمتنا بسيطة: تحويل التوجيه إلى رافعة حقيقية للفرص.",
    "about.context": "كل عام، يختار آلاف الطلاب تخصصاً لا يناسبهم، ويتخلى طلاب آخرون بسبب نقص المعلومات الموثوقة، ويجد الخريجون صعوبة في إيجاد تدريب أو وظيفة مناسبة. كانت هذه الملاحظة نقطة البداية لإنشاء NextStep: تقديم مساحة واضحة وموثوقة ومنظمة لتوجيه كل شاب، خطوة بخطوة.",
    "about.vision.title": "رؤيتنا",
    "about.vision.content": "جعل التوجيه أداة استراتيجية تمكن كل شاب من بناء مستقبل متين ومستنير ومتوافق مع طموحاته.",
    "about.mission.title": "مهمتنا",
    "about.mission.intro": "مرافقة الشباب في مساراتهم:",
    "about.mission.point1.title": "التوجيه الأكاديمي:",
    "about.mission.point1.desc": "اختبارات موثوقة ومسارات موصى بها.",
    "about.mission.point2.title": "الاندماج المهني:",
    "about.mission.point2.desc": "عروض تدريب، قوالب سيرة ذاتية، تدريب.",
    "about.mission.point3.title": "دعم ريادة الأعمال:",
    "about.mission.point3.desc": "أدلة خطوة بخطوة، أدوات دراسة السوق، الوصول لمنظمات التمويل.",
    "about.why.title": "لماذا أنشأنا NextStep؟",
    "about.why.intro": "لأن الشباب غالباً ما يفتقرون إلى:",
    "about.why.point1": "معلومات مركزة ومفهومة،",
    "about.why.point2": "مرافقة شخصية،",
    "about.why.point3": "خطة واضحة للتقدم.",
    "about.why.conclusion": "هدفنا هو تبسيط اتخاذ القرار، تقليل الارتباك، ومساعدة كل شاب على التقدم بثقة.",
    "about.value.title": "قيمتنا المضافة",
    "about.value.intro": "تقدم NextStep:",
    "about.value.point1": "أداة بسيطة وحديثة وبديهية،",
    "about.value.point2": "مرافقة خبيرة ومخصصة،",
    "about.value.point3": "وصول مباشر للفرص الأكاديمية والمهنية وريادة الأعمال،",
    "about.value.point4": "مسار موجه للتطور خطوة بخطوة.",
    "about.slogan": "Build your future",
    "about.closing": "بفضل هوية بصرية قوية وشعار ملهم ونهج متمحور حول المستخدم، تتموضع NextStep كمنصة أساسية للتقدم نحو مستقبل متقن.",
    // Login page
    "login.title": "مرحباً بعودتك!",
    "login.subtitle": "سجل الدخول لمتابعة مسارك.",
    "login.google": "المتابعة مع Google",
    "login.or": "أو",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.forgot": "نسيت كلمة المرور؟",
    "login.submit": "تسجيل الدخول",
    "login.noAccount": "ليس لديك حساب؟",
    "login.register": "سجل مجاناً",
    "login.welcome": "مرحباً في NEXT STEP",
    "login.welcomeDesc": "المنصة التي ترافقك نحو نجاحك المهني في المغرب.",
    // Register page
    "register.title": "إنشاء حساب",
    "register.subtitle": "ابدأ رحلتك نحو النجاح.",
    "register.google": "التسجيل مع Google",
    "register.or": "أو",
    "register.name": "الاسم الكامل",
    "register.email": "البريد الإلكتروني",
    "register.password": "كلمة المرور (8 أحرف على الأقل)",
    "register.terms": "بالتسجيل، أنت توافق على",
    "register.termsLink": "شروط الاستخدام",
    "register.and": "و",
    "register.privacyLink": "سياسة الخصوصية",
    "register.submit": "إنشاء حسابي",
    "register.hasAccount": "لديك حساب بالفعل؟",
    "register.login": "تسجيل الدخول",
    "register.heroTitle": "ابنِ مستقبلك مع",
    "register.heroDesc": "انضم إلى آلاف المغاربة الذين تحكموا في مستقبلهم.",
    "register.benefit1": "اختبارات توجيه مخصصة",
    "register.benefit2": "الوصول لعروض التدريب",
    "register.benefit3": "أدلة ريادة الأعمال الشاملة",
    "register.benefit4": "موارد السيرة الذاتية والمقابلات",
    // Orientation additional
    "orientation.level.beginner": "مبتدئ",
    "orientation.level.intermediate": "متوسط",
    "orientation.path.marketing.desc": "أتقن أساسيات التسويق الرقمي.",
    "orientation.path.dev.desc": "كن مطور ويب متكامل.",
    "orientation.path.project.desc": "تعلم إدارة المشاريع بمرونة.",
    // Entrepreneuriat additional
    "entrepreneuriat.statut.auto.desc": "مثالي للبدء وحدك مع إجراءات قليلة",
    "entrepreneuriat.statut.auto.adv1": "لا حد أدنى لرأس المال",
    "entrepreneuriat.statut.auto.adv2": "محاسبة مبسطة",
    "entrepreneuriat.statut.auto.adv3": "رسوم مخفضة",
    "entrepreneuriat.statut.auto.best": "المستقلون، المستشارون، التجارة الصغيرة",
    "entrepreneuriat.statut.sarl.desc": "هيكل كلاسيكي للشركات الصغيرة والمتوسطة",
    "entrepreneuriat.statut.sarl.adv1": "مسؤولية محدودة",
    "entrepreneuriat.statut.sarl.adv2": "مصداقية متزايدة",
    "entrepreneuriat.statut.sarl.adv3": "إمكانية الشراكة",
    "entrepreneuriat.statut.sarl.best": "الشركات الصغيرة والمتوسطة، مشاريع النمو المعتدل",
    "entrepreneuriat.statut.sa.desc": "للمشاريع الطموحة",
    "entrepreneuriat.statut.sa.adv1": "تسهيل جمع الأموال",
    "entrepreneuriat.statut.sa.adv2": "صورة احترافية",
    "entrepreneuriat.statut.sa.adv3": "إمكانية الإدراج",
    "entrepreneuriat.statut.sa.best": "الشركات الناشئة، المشاريع الكبيرة، جمع الأموال",
    // Blog page
    "blog.badge": "أخبار ونصائح",
    "blog.page.title": "أخبار و",
    "blog.page.title.highlight": "نصائح",
    "blog.title": "نصائح و",
    "blog.title.highlight": "إلهامات",
    "blog.description": "مقالات وأدلة وشهادات لمرافقتك في مسارك.",
    "blog.category.all": "الكل",
    "blog.category.orientation": "التوجيه",
    "blog.category.stages": "التدريب والعمل",
    "blog.category.entrepreneuriat": "ريادة الأعمال",
    "blog.category.career": "المهنة",
    "blog.featured.title": "كيف تنجح في تغيير مسارك المهني في المغرب 2024",
    "blog.featured.excerpt": "دليل شامل لتغيير المهنة بنجاح. اكتشف الخطوات الرئيسية والأخطاء التي يجب تجنبها وفرص السوق المغربي.",
    "blog.featured.author": "فريق NEXT STEP",
    "blog.featured.date": "5 ديسمبر 2024",
    "blog.featured.readTime": "8 دقائق",
    "blog.readTime": "قراءة",
    "blog.readArticle": "اقرأ المقال",
    "blog.latestArticles": "آخر المقالات",
    "blog.loadMore": "تحميل المزيد",
    "blog.post1.title": "أفضل 10 قطاعات توظف المتدربين",
    "blog.post1.excerpt": "اكتشف المجالات الواعدة للحصول على تدريبك.",
    "blog.post1.date": "3 ديسمبر 2024",
    "blog.post2.title": "إنشاء مشروع: الأخطاء التي يجب تجنبها",
    "blog.post2.excerpt": "الفخاخ الكلاسيكية للمقاولين الشباب وكيفية تجنبها.",
    "blog.post2.date": "1 ديسمبر 2024",
    "blog.post3.title": "كتابة سيرة ذاتية متميزة",
    "blog.post3.excerpt": "نصائح عملية لإنشاء سيرة ذاتية مقنعة مكيفة للسوق المغربي.",
    "blog.post3.date": "28 نوفمبر 2024",
    "blog.post4.title": "المهارات الشخصية الأكثر طلباً في 2024",
    "blog.post4.excerpt": "ما المهارات السلوكية التي يجب تطويرها لتعزيز حياتك المهنية.",
    "blog.post4.date": "25 نوفمبر 2024",
    "blog.post5.title": "تمويل شركتك الناشئة: دليل شامل",
    "blog.post5.excerpt": "جميع خيارات التمويل المتاحة للمقاولين المغاربة.",
    "blog.post5.date": "22 نوفمبر 2024",
    "blog.newsletter.title": "ابق على اطلاع",
    "blog.newsletter.description": "تلقَّ أفضل نصائحنا وأخبارنا مباشرة في بريدك.",
    "blog.newsletter.placeholder": "بريدك الإلكتروني",
    "blog.newsletter.subscribe": "اشترك",
    // FAQ page
    "faq.badge": "الأسئلة الشائعة",
    "faq.title": "الأسئلة",
    "faq.title.highlight": "الشائعة",
    "faq.description": "اعثر على إجابات لأسئلتك الأكثر شيوعاً حول NEXT STEP.",
    "faq.q1": "ما هو NEXT STEP؟",
    "faq.a1": "NEXT STEP هي منصة شاملة مخصصة للتوجيه الأكاديمي والاندماج المهني ودعم ريادة الأعمال في المغرب. نساعد الشباب على بناء مستقبلهم بثقة.",
    "faq.q2": "كيف يعمل اختبار التوجيه؟",
    "faq.a2": "يعتمد اختبار التوجيه لدينا على طرق نفسية موثقة. يحلل اهتماماتك ومهاراتك وقيمك ليوصي بالمسارات الأنسب لملفك الشخصي.",
    "faq.q3": "هل عروض التدريب موثقة؟",
    "faq.a3": "نعم، جميع عروض التدريب والتوظيف المنشورة على NEXT STEP يتم التحقق منها من قبل فريقنا لضمان صحتها وجودتها.",
    "faq.q4": "كيف يمكنني الوصول للموارد المميزة؟",
    "faq.a4": "الموارد المميزة متاحة من خلال خططنا المختلفة. اختر الخطة المناسبة لاحتياجاتك لفتح الوصول لقوالب السيرة الذاتية ورسائل التقديم والتدريب الشخصي.",
    "faq.q5": "هل تقدمون دعماً لإنشاء مشروع؟",
    "faq.a5": "بالتأكيد! خطة دعم ريادة الأعمال لدينا تشمل أدلة شاملة وقوالب خطط العمل والوصول لمنظمات التمويل المغربية والتدريب الشخصي.",
    "faq.q6": "هل يمكنني إلغاء اشتراكي في أي وقت؟",
    "faq.a6": "نعم، جميع خططنا بدون التزام. يمكنك الإلغاء في أي وقت دون رسوم إضافية.",
    "faq.q7": "كيف أتواصل مع الدعم؟",
    "faq.a7": "يمكنك التواصل معنا عبر البريد الإلكتروني على contact@nextstep.ma. فريقنا يرد عادة خلال 24 ساعة.",
    "faq.q8": "هل NEXT STEP متاح بعدة لغات؟",
    "faq.a8": "نعم، NEXT STEP متاح بالفرنسية والإنجليزية والعربية لخدمة مجتمعنا المتنوع في المغرب بشكل أفضل.",
    "faq.contact.text": "لم تجد إجابة لسؤالك؟ تواصل معنا:",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
